from lib import add

add(
    "jebel-irhoud",
    "Homo sapiens at Jebel Irhoud",
    "history",
    -300000,
    -300000,
    31.86,
    -8.87,
    "Jebel Irhoud, Morocco",
    "Africa",
    "Fossil skulls at Jebel Irhoud are widely dated to about 300,000 years ago and are among the oldest known Homo sapiens. They combine a modern-looking face with a more archaic braincase. The finds place our species in north-west Africa by about 300,000 years ago.",
    "Approximate. The fossils are widely dated to about 300,000 years ago.",
)
add(
    "homo-naledi",
    "Homo naledi in the Rising Star caves",
    "history",
    -300000,
    -236000,
    -25.91,
    27.78,
    "Rising Star cave, South Africa",
    "Africa",
    "Homo naledi is a small-brained hominin known from a deep cave system north-west of Johannesburg. The remains are dated to roughly 335,000 to 236,000 years ago, so the later part of that span falls within the last 300,000 years. How the bodies entered the chamber is still debated.",
    "Approximate. The published age is about 335,000 to 236,000 years ago.",
)
add(
    "omo-kibish",
    "Omo Kibish fossils",
    "history",
    -233000,
    -233000,
    4.80,
    35.97,
    "Omo Kibish, Ethiopia",
    "Africa",
    "Fossils from the Kibish Formation near the Omo River are among the oldest widely accepted Homo sapiens remains in eastern Africa. A 2022 study dated the deposits to at least about 233,000 years ago. They show that people with modern anatomy were in the Rift Valley long before later dispersals.",
    "Approximate. The deposits are dated to at least about 233,000 years ago.",
)
add(
    "herto",
    "Herto humans",
    "history",
    -160000,
    -154000,
    10.26,
    40.56,
    "Herto, Middle Awash, Ethiopia",
    "Africa",
    "Skulls from Herto in the Afar are widely dated to about 160,000 to 154,000 years ago. They are often classed as Homo sapiens idaltu, an early form of our species. Cut marks on one skull have been read as signs of mortuary practice, though that reading is cautious.",
    "Approximate. The skulls are widely dated to about 160,000 to 154,000 years ago.",
)
add(
    "blombos-symbols",
    "Engraved ochre at Blombos Cave",
    "history",
    -77000,
    -73000,
    -34.41,
    21.22,
    "Blombos Cave, South Africa",
    "Africa",
    "Blombos Cave has engraved ochre pieces and shell beads dated to roughly 77,000 to 73,000 years ago. The cross-hatched ochre is among the oldest widely accepted marks made as a design. The beads suggest that people were already using ornaments.",
    "Approximate. The objects are dated to about 77,000 to 73,000 years ago.",
)
add(
    "apollo-11-stones",
    "Painted slabs from Apollo 11 Cave",
    "history",
    -27000,
    -25000,
    -27.68,
    17.10,
    "Apollo 11 Cave, Namibia",
    "Africa",
    "Seven painted stone slabs from Apollo 11 Cave in southern Namibia are among the oldest known paintings in Africa. They are widely dated to about 25,000 to 27,000 years ago. The images include animals painted on loose stones rather than on the cave wall.",
    "Approximate. The slabs are widely dated to about 25,000 to 27,000 years ago.",
)
add(
    "out-of-africa",
    "Out of Africa",
    "history",
    -65000,
    -50000,
    6.0,
    36.0,
    "East African Rift",
    "Africa",
    "Genetic and archaeological evidence points to a major dispersal of Homo sapiens out of Africa roughly 70,000 to 50,000 years ago. People moved through the Horn and into southern Asia over many generations. The line is a schematic of that southern route, not a single journey.",
    "Approximate. The main dispersal is widely placed at about 70,000 to 50,000 years ago.",
    path=[
        (6.0, 36.0),
        (11.5, 42.0),
        (12.6, 43.4),
        (16.0, 49.0),
        (25.5, 56.5),
        (23.0, 68.5),
        (21.0, 87.0),
        (7.0, 100.0),
        (1.3, 103.8),
    ],
)
add(
    "bantu-expansion",
    "Bantu expansion",
    "history",
    -1000,
    500,
    6.4,
    10.4,
    "Cameroon highlands",
    "Africa",
    "Speakers of Bantu languages spread from the Cameroon–Nigeria borderlands into central, eastern, and southern Africa. The movement is widely placed from about 1000 BCE into the early centuries CE, and it carried farming and, later, ironworking. The line is a schematic of the main branches, not one migration.",
    "Approximate. The expansion is widely dated from about 1000 BCE into the early first millennium CE.",
    path=[
        (6.4, 10.4),
        (2.0, 17.0),
        (-1.5, 29.0),
        (-3.0, 37.5),
        (-15.0, 30.0),
        (-25.5, 28.5),
    ],
)
add(
    "narmer-palette",
    "Unification of Egypt",
    "history",
    -3100,
    -3000,
    26.18,
    31.92,
    "Abydos, Egypt",
    "Africa",
    "Late predynastic objects, including the Narmer Palette, depict a ruler of Upper Egypt subduing the north. Egypt was joined into one kingdom around 3100 BCE, with Abydos an early royal cemetery. The exact year and the role of one king named Narmer remain approximate.",
    "Approximate. Unification is widely placed around 3100 BCE.",
)
add(
    "early-cuneiform",
    "Early writing in Mesopotamia",
    "history",
    -3400,
    -3000,
    31.32,
    45.64,
    "Uruk, Iraq",
    "Asia",
    "At Uruk, clay tablets with pictographic signs appear in the late fourth millennium BCE. They tracked goods and labour, and they developed into cuneiform. The tablets belong to the centuries just before and around 3000 BCE.",
    "Approximate. The earliest tablets are widely dated to about 3400–3000 BCE.",
)
add(
    "great-pyramid",
    "Great Pyramid of Khufu",
    "history",
    -2580,
    -2560,
    29.98,
    31.13,
    "Giza, Egypt",
    "Africa",
    "The Great Pyramid at Giza was built for the king Khufu in the Fourth Dynasty. It is widely dated to the decades around 2580–2560 BCE. It remained the tallest human structure for most of later history.",
    "Approximate. Khufu's reign is widely placed in the 26th century BCE.",
)
add(
    "kerma",
    "Kingdom of Kerma",
    "history",
    -2500,
    -1500,
    19.64,
    30.41,
    "Kerma, Sudan",
    "Africa",
    "Kerma, on the Nile in Nubia, was a powerful city-state trading and at times fighting with Egypt. Its classic phase is widely dated to about 2500–1500 BCE. Huge earthen tumuli at the site mark its rulers.",
    "Approximate. The classic Kerma kingdom is widely dated to about 2500–1500 BCE.",
)
add(
    "hatshepsut",
    "Reign of Hatshepsut",
    "history",
    -1479,
    -1458,
    25.74,
    32.61,
    "Deir el-Bahri, Egypt",
    "Africa",
    "Hatshepsut ruled Egypt as pharaoh in the early Eighteenth Dynasty and built a terraced temple at Deir el-Bahri. Her reign is widely dated to about 1479–1458 BCE. Reliefs there record an expedition to Punt, somewhere on the Red Sea coast of Africa.",
    "Approximate. Her reign is widely dated to about 1479–1458 BCE.",
)
add(
    "akhenaten",
    "Akhenaten's new capital",
    "history",
    -1353,
    -1336,
    27.65,
    30.90,
    "Amarna, Egypt",
    "Africa",
    "Akhenaten promoted the cult of the Aten and founded a new capital at Amarna. His reign is widely placed in the mid-fourteenth century BCE. After his death the court returned to Thebes and the experiment was abandoned.",
    "Approximate. The Amarna period is widely placed in the mid-fourteenth century BCE.",
)
add(
    "ramesses-ii",
    "Reign of Ramesses II",
    "history",
    -1279,
    -1213,
    25.73,
    32.63,
    "Thebes and Pi-Ramesses, Egypt",
    "Africa",
    "Ramesses II ruled Egypt for much of the thirteenth century BCE and built on a huge scale, including Abu Simbel. His reign is widely dated to about 1279–1213 BCE. He also fought the Hittites at Kadesh and later made a treaty with them.",
    "Approximate. His reign is widely dated to about 1279–1213 BCE.",
)
add(
    "merneptah-stele",
    "Merneptah Stele",
    "history",
    -1208,
    -1208,
    25.70,
    32.64,
    "Thebes, Egypt",
    "Africa",
    "A victory inscription of the pharaoh Merneptah, dated to about 1208 BCE, lists a people called Israel in Canaan. It is the earliest widely accepted mention of that name. The text celebrates Egyptian campaigns, not a history of Israel itself.",
    "The stele is widely dated to Merneptah's fifth year, about 1208 BCE.",
)
add(
    "nok-culture",
    "Nok culture",
    "history",
    -1500,
    -300,
    9.50,
    8.00,
    "Jos Plateau, Nigeria",
    "Africa",
    "The Nok culture of central Nigeria produced distinctive terracotta figures and, later, iron. It is widely dated from about 1500 BCE to the early centuries CE, with iron well established by the mid-first millennium BCE. Many of the sculptures were found in tin mines.",
    "Approximate. Nok terracottas and ironworking are widely placed from about 1500 BCE onward.",
)
add(
    "kush-napata",
    "Kushite kings in Egypt",
    "history",
    -747,
    -656,
    18.53,
    31.82,
    "Napata, Sudan",
    "Africa",
    "Kings from Kush, centred at Napata, conquered Egypt in the eighth century BCE and ruled as the Twenty-fifth Dynasty. Their rule there is widely dated to about 747–656 BCE. They were later pushed back up the Nile by Assyrian campaigns.",
    "Approximate. The Kushite dynasty in Egypt is widely dated to about 747–656 BCE.",
)
add(
    "meroe",
    "Royal city of Meroë",
    "history",
    -300,
    350,
    16.94,
    33.75,
    "Meroë, Sudan",
    "Africa",
    "Meroë became the royal centre of Kush and a major ironworking city. Its heyday runs from about the third century BCE to the fourth century CE. Rulers, including reigning queens, were buried under steep pyramids nearby.",
    "Approximate. Meroë's royal period is widely placed from about 300 BCE to 350 CE.",
)
add(
    "carthage-punic",
    "Carthage and Rome",
    "history",
    -264,
    -146,
    36.85,
    10.32,
    "Carthage, Tunisia",
    "Africa",
    "Carthage, a Phoenician foundation in what is now Tunisia, fought three wars with Rome between 264 and 146 BCE. Rome destroyed the city in 146 BCE after the Third Punic War. The traditional foundation date of 814 BCE is less secure than these war years.",
    "The Punic Wars are dated from 264 to 146 BCE.",
)
add(
    "cleopatra-actium",
    "Death of Cleopatra",
    "history",
    -30,
    -30,
    31.20,
    29.92,
    "Alexandria, Egypt",
    "Africa",
    "Cleopatra VII, the last Ptolemaic ruler of Egypt, died in 30 BCE after Rome defeated her and Mark Antony. Egypt then became a Roman province. Ancient accounts of the manner of her death differ in their details.",
    "Her death is dated to 30 BCE.",
)
add(
    "aksum-ezana",
    "Ezana of Aksum",
    "history",
    330,
    360,
    14.13,
    38.72,
    "Aksum, Ethiopia",
    "Africa",
    "Ezana ruled the kingdom of Aksum in the fourth century and issued inscriptions and coins. During his reign the court adopted Christianity. Aksum controlled Red Sea trade and, for a time, parts of southern Arabia.",
    "Approximate. Ezana's reign is widely placed in the mid-fourth century CE.",
)
add(
    "ghana-empire",
    "Kingdom of Ghana",
    "history",
    800,
    1100,
    15.70,
    -9.50,
    "Koumbi Saleh, Mauritania",
    "Africa",
    "The kingdom called Ghana by Arab writers dominated the savanna trade in gold and salt. Its height is widely placed between about 800 and 1100. The capital is often identified with Koumbi Saleh, though that identification is not certain.",
    "Approximate. Arab geographers describe the kingdom in these centuries.",
)
add(
    "swahili-kilwa",
    "Kilwa and the Swahili coast",
    "history",
    1000,
    1500,
    -8.96,
    39.51,
    "Kilwa, Tanzania",
    "Africa",
    "Stone towns along the East African coast, linked by the Swahili language, traded gold, ivory, and timber across the Indian Ocean. Kilwa was a leading port from about the eleventh to the fifteenth century. Its Great Mosque still stands.",
    "Approximate. Kilwa's peak is widely placed between about 1000 and 1500.",
)
add(
    "lalibela",
    "Rock churches of Lalibela",
    "history",
    1180,
    1220,
    12.03,
    39.04,
    "Lalibela, Ethiopia",
    "Africa",
    "Churches cut from living rock at Lalibela are traditionally linked to the Zagwe king Gebre Meskel Lalibela. They are widely dated to around the late twelfth and early thirteenth centuries. The town remains a major Christian pilgrimage site.",
    "Approximate. The churches are widely dated to about 1180–1220.",
)
add(
    "mali-founding",
    "Founding of the Mali Empire",
    "history",
    1235,
    1255,
    11.30,
    -8.00,
    "Upper Niger, Guinea and Mali",
    "Africa",
    "Sundiata Keita defeated the Soso king Sumanguru at the battle of Kirina, widely placed in about 1235, and built the Mali Empire. Mali then controlled long-distance trade across the western savanna. The epic told about Sundiata is a later oral tradition.",
    "Approximate. Kirina is widely placed in about 1235.",
)
add(
    "great-zimbabwe",
    "Great Zimbabwe",
    "history",
    1100,
    1450,
    -20.27,
    30.93,
    "Great Zimbabwe",
    "Africa",
    "Great Zimbabwe was the stone-built capital of a Shona kingdom that traded gold to the Indian Ocean coast. Its main occupation is widely dated from about the eleventh to the fifteenth century. The site was built by local African masons, a point long established by archaeology.",
    "Approximate. The stone city flourished from about 1100 to 1450.",
)
add(
    "mansa-musa",
    "Mansa Musa's pilgrimage",
    "history",
    1324,
    1325,
    16.77,
    -3.00,
    "Timbuktu and Cairo",
    "Africa",
    "Mansa Musa, ruler of Mali, travelled to Mecca in 1324–1325 and passed through Cairo with a very large supply of gold. Contemporary writers in Egypt described the journey and its effect on the gold market. He also sponsored mosques and learning in Timbuktu.",
    "The hajj is dated to 1324–1325.",
)
add(
    "songhai-timbuktu",
    "Songhai takes Timbuktu",
    "history",
    1468,
    1468,
    16.77,
    -3.00,
    "Timbuktu, Mali",
    "Africa",
    "Sunni Ali of Songhai took Timbuktu in 1468 and expanded a empire along the Niger bend. The city stayed a centre of manuscript learning under Songhai rule. Moroccan forces later defeated Songhai in 1591.",
    "Sunni Ali's capture of Timbuktu is dated to 1468.",
)
add(
    "kongo-portugal",
    "Kongo meets Portugal",
    "history",
    1483,
    1491,
    -6.27,
    14.24,
    "Mbanza Kongo, Angola",
    "Africa",
    "Portuguese ships reached the kingdom of Kongo in 1483, and King Nzinga a Nkuwu was baptised in 1491. The contact began a long and unequal relationship, including the trade in enslaved people. Kongo remained an independent kingdom for centuries after.",
    "The first Portuguese embassy is dated to 1483, and the royal baptism to 1491.",
)
add(
    "benin-city-walls",
    "Walls of Benin City",
    "history",
    1450,
    1600,
    6.34,
    5.62,
    "Benin City, Nigeria",
    "Africa",
    "The kingdom of Benin built a vast system of earth walls and ditches around its capital and the surrounding landscape. Much of the monumental work is dated to the fifteenth and sixteenth centuries. Brass plaques from the court, later looted in 1897, record its history.",
    "Approximate. The major earthworks are widely placed in the fifteenth and sixteenth centuries.",
)
add(
    "sokoto-caliphate",
    "Sokoto Caliphate",
    "history",
    1804,
    1808,
    13.06,
    5.24,
    "Sokoto, Nigeria",
    "Africa",
    "Usman dan Fodio led a jihad from 1804 that overthrew Hausa rulers and founded the Sokoto Caliphate. By 1808 the new state was the largest in West Africa. It lasted until British conquest in the early twentieth century.",
    "The jihad began in 1804.",
)
add(
    "shaka-zulu",
    "Rise of the Zulu kingdom",
    "history",
    1816,
    1828,
    -28.55,
    31.40,
    "KwaZulu-Natal, South Africa",
    "Africa",
    "Shaka kaSenzangakhona built a centralised Zulu kingdom in the late 1810s and 1820s. The wars of that period reshaped societies across southern Africa. Many vivid details in later biographies of Shaka are disputed, but the rise of the kingdom is not.",
    "Approximate. Shaka's reign is widely placed from about 1816 to 1828.",
)
add(
    "champollion",
    "Decipherment of hieroglyphs",
    "history",
    1822,
    1822,
    48.85,
    2.35,
    "Paris, France",
    "Europe",
    "In 1822 Jean-François Champollion announced that he could read ancient Egyptian hieroglyphs, using the Rosetta Stone and other bilingual texts. The decipherment opened three thousand years of Egyptian writing to modern study. The stone itself had been found by French soldiers in 1799.",
    "Champollion's letter to Dacier is dated 27 September 1822.",
)
add(
    "liberia-independence",
    "Independence of Liberia",
    "history",
    1847,
    1847,
    6.30,
    -10.80,
    "Monrovia, Liberia",
    "Africa",
    "Settlers from the United States declared the Republic of Liberia in 1847. The new state was not ruled by a European colonial power, but it also excluded many indigenous people from power. Its capital was named for the American president James Monroe.",
    "Independence was declared on 26 July 1847.",
)
add(
    "adwa",
    "Battle of Adwa",
    "history",
    1896,
    1896,
    14.15,
    38.90,
    "Adwa, Ethiopia",
    "Africa",
    "On 1 March 1896 Ethiopian armies under Emperor Menelik II defeated an Italian invasion at Adwa. The victory preserved Ethiopian independence during the European partition of Africa. It became a symbol for later anti-colonial movements.",
    "The battle was fought on 1 March 1896.",
)
add(
    "benin-expedition",
    "Looting of Benin City",
    "history",
    1897,
    1897,
    6.34,
    5.62,
    "Benin City, Nigeria",
    "Africa",
    "In 1897 a British punitive expedition burned Benin City and seized thousands of royal plaques and sculptures. The objects were sold to museums and collectors in Europe. Many are now the subject of return claims by Nigeria.",
    "The expedition took the city in February 1897.",
)
add(
    "herero-nama",
    "Genocide of the Herero and Nama",
    "history",
    1904,
    1908,
    -22.56,
    17.08,
    "German South West Africa",
    "Africa",
    "From 1904 German colonial troops crushed Herero and Nama resistance in what is now Namibia. People were driven into the desert and survivors were held in camps. The campaign is widely recognised as a genocide.",
    "The war and the camps are dated to 1904–1908.",
)
add(
    "maji-maji",
    "Maji Maji uprising",
    "history",
    1905,
    1907,
    -8.90,
    33.45,
    "Southern German East Africa",
    "Africa",
    "In 1905 people across southern German East Africa rose against forced cotton growing and colonial rule. The uprising, called Maji Maji, was defeated by 1907. Famine that followed the German scorched-earth response killed very large numbers.",
    "The uprising is dated to 1905–1907.",
)
add(
    "italy-ethiopia-1935",
    "Italian invasion of Ethiopia",
    "history",
    1935,
    1936,
    9.03,
    38.74,
    "Addis Ababa, Ethiopia",
    "Africa",
    "Fascist Italy invaded Ethiopia in October 1935 and occupied Addis Ababa in May 1936. Emperor Haile Selassie appealed to the League of Nations, which failed to stop the conquest. Ethiopian and Allied forces drove the Italians out in 1941.",
    "The invasion began on 3 October 1935.",
)
add(
    "apartheid-1948",
    "Apartheid government",
    "history",
    1948,
    1948,
    -25.75,
    28.19,
    "Pretoria, South Africa",
    "Africa",
    "In 1948 the National Party won power in South Africa and extended racial segregation into the system called apartheid. Later laws classified people by race and forced millions into separate areas. The system lasted until the election of 1994.",
    "The National Party took office after the election of 26 May 1948.",
)
add(
    "ghana-independence",
    "Independence of Ghana",
    "history",
    1957,
    1957,
    5.56,
    -0.21,
    "Accra, Ghana",
    "Africa",
    "The Gold Coast became independent Ghana on 6 March 1957, with Kwame Nkrumah as prime minister. It was the first colony in sub-Saharan Africa to win independence from European rule in that wave. Nkrumah made Accra a centre of pan-African politics.",
    "Independence was declared on 6 March 1957.",
)
add(
    "year-of-africa",
    "Year of Africa",
    "history",
    1960,
    1960,
    4.39,
    18.56,
    "Africa",
    "Africa",
    "In 1960 seventeen African countries became independent, most of them from France. The year is often called the Year of Africa. It marked the rapid end of formal colonial rule across much of the continent.",
    "Seventeen independences fell in the calendar year 1960.",
)
add(
    "sharpeville",
    "Sharpeville massacre",
    "history",
    1960,
    1960,
    -26.69,
    27.87,
    "Sharpeville, South Africa",
    "Africa",
    "On 21 March 1960 police fired on a crowd protesting pass laws at Sharpeville, killing 69 people. The government then banned the African National Congress and the Pan Africanist Congress. The date is now honoured as Human Rights Day in South Africa.",
    "The shooting was on 21 March 1960.",
)
add(
    "algerian-independence",
    "Independence of Algeria",
    "history",
    1962,
    1962,
    36.75,
    3.06,
    "Algiers, Algeria",
    "Africa",
    "A war against French rule ran from 1954 until the Evian Accords of 1962. Algeria declared independence on 5 July 1962 after a referendum. The war killed very large numbers of Algerians and ended more than 130 years of French colonisation.",
    "Independence was proclaimed on 5 July 1962.",
)
add(
    "biafra",
    "Nigerian Civil War",
    "history",
    1967,
    1970,
    6.45,
    7.51,
    "South-eastern Nigeria",
    "Africa",
    "The Eastern Region seceded as Biafra in 1967, and the Nigerian federal government fought to restore the union until 1970. A blockade caused a famine that was seen around the world. Biafra surrendered in January 1970.",
    "The war is dated from 6 July 1967 to 15 January 1970.",
)
add(
    "soweto",
    "Soweto uprising",
    "history",
    1976,
    1976,
    -26.27,
    27.86,
    "Soweto, South Africa",
    "Africa",
    "On 16 June 1976 students in Soweto marched against schooling in Afrikaans. Police opened fire, and the protests spread across South Africa. The uprising is often marked by the photograph of the dying Hector Pieterson, aged twelve.",
    "The march was on 16 June 1976.",
)
add(
    "lucy-discovery",
    "Discovery of Lucy",
    "history",
    1974,
    1974,
    11.13,
    40.58,
    "Hadar, Ethiopia",
    "Africa",
    "In 1974 a team at Hadar found a partial skeleton of Australopithecus afarensis, nicknamed Lucy. The fossil itself is about 3.2 million years old, far older than the last 300,000 years. The discovery changed the public picture of early human ancestors.",
    "The skeleton was found on 24 November 1974. The fossil is much older than 300,000 BCE.",
)
add(
    "mandela-1994",
    "Election of Nelson Mandela",
    "history",
    1994,
    1994,
    -33.93,
    18.42,
    "Cape Town, South Africa",
    "Africa",
    "South Africa held its first election with universal adult suffrage in April 1994, and Nelson Mandela became president. The vote ended formal apartheid. Mandela had been released from prison in 1990 after 27 years.",
    "The election was held on 27 April 1994.",
)
add(
    "rwanda-genocide",
    "Genocide against the Tutsi",
    "history",
    1994,
    1994,
    -1.94,
    30.06,
    "Kigali, Rwanda",
    "Africa",
    "Between April and July 1994 extremists in Rwanda organised the murder of hundreds of thousands of Tutsi, and of Hutu who opposed the killing. The genocide unfolded in about one hundred days while a civil war continued. An international tribunal later judged the killings a genocide.",
    "The genocide is dated from 7 April to mid-July 1994.",
)
add(
    "south-sudan",
    "Independence of South Sudan",
    "history",
    2011,
    2011,
    4.85,
    31.58,
    "Juba, South Sudan",
    "Africa",
    "After a long civil war and a 2011 referendum, South Sudan became independent on 9 July 2011. It was the newest widely recognised state in Africa. A further civil war began inside the country in 2013.",
    "Independence was on 9 July 2011.",
)
add(
    "tunisian-revolution",
    "Tunisian revolution",
    "history",
    2010,
    2011,
    36.81,
    10.18,
    "Tunis, Tunisia",
    "Africa",
    "Protests beginning in December 2010 forced President Zine El Abidine Ben Ali from office in January 2011. The uprising started a wave of revolts across the Arab world. Tunisia later adopted a new constitution, though politics remained contested.",
    "Ben Ali left office on 14 January 2011.",
)
add(
    "osiris-myth",
    "Myth of Osiris",
    "myth",
    -2400,
    -2300,
    26.18,
    31.92,
    "Abydos, Egypt",
    "Africa",
    "Osiris, killed and restored as ruler of the dead, is a central figure of Egyptian religion and is especially tied to Abydos. The story is already present in the Pyramid Texts of the Old Kingdom. Later tellings, including Plutarch's, are much younger than those inscriptions.",
    "Earliest written source. The Pyramid Texts, from about the 24th century BCE, already refer to Osiris.",
)
add(
    "ile-ife-myth",
    "Creation at Ile-Ife",
    "myth",
    1850,
    1890,
    7.48,
    4.56,
    "Ile-Ife, Nigeria",
    "Africa",
    "Yoruba tradition places the creation of the world and the first kingship at Ile-Ife. The oral religion is far older than any book. Substantial written accounts of these traditions were set down by Yoruba and European authors in the nineteenth century.",
    "Earliest written source. Nineteenth-century writers recorded traditions that are much older.",
)
add(
    "sundiata-epic",
    "Epic of Sundiata",
    "myth",
    1960,
    1960,
    11.30,
    -8.00,
    "Upper Niger",
    "Africa",
    "Griots have long told the epic of Sundiata, the founder of Mali, blending a thirteenth-century ruler with marvels and prophecy. The historical founding of Mali is a separate historical episode. Full versions of the epic were written down from oral performance in the twentieth century.",
    "Earliest written source. Widely circulated written versions were recorded from oral performance in the twentieth century. The tradition is medieval.",
)
add(
    "mwindo-epic",
    "Epic of Mwindo",
    "myth",
    1950,
    1969,
    -1.20,
    28.80,
    "Nyanga country, eastern Congo",
    "Africa",
    "The Nyanga epic of Mwindo tells of a miraculous child who quarrels with his father and travels to the realm of the gods. It was an oral tradition until Daniel Biebuyck recorded performances and published them. The story belongs to the Nyanga people of the eastern Congo forests.",
    "Earliest written source. Biebuyck's publications of the 1950s and 1960s are the first full written texts. The oral epic is older.",
)
