from lib import add

add(
    "peopling-of-the-americas",
    "Peopling of the Americas",
    "history",
    -14000,
    -12000,
    65.0,
    -168.0,
    "Beringia",
    "North America",
    "People reached the Americas from north-east Asia while sea levels were low, and by about 14,500 years ago they were as far south as Chile. The widely accepted window for this spread is about 16,000 to 14,000 years ago. The line is a schematic through Beringia and down the continents. Earlier sites are still debated.",
    "Approximate. Widespread settlement is dated to about 16,000–14,000 years ago. The years stored here are the BCE equivalents.",
    path=[
        (66.0, 170.0),
        (65.5, -168.0),
        (64.5, -155.0),
        (55.0, -131.0),
        (34.0, -118.0),
        (19.4, -99.1),
        (9.0, -79.5),
        (4.6, -74.1),
        (-13.5, -72.0),
        (-41.5, -73.2),
    ],
)
add(
    "monte-verde",
    "Monte Verde",
    "history",
    -12500,
    -12500,
    -41.50,
    -73.20,
    "Monte Verde, Chile",
    "South America",
    "Monte Verde, near Puerto Montt, was occupied about 14,500 years ago, around 12,500 BCE. Wooden remains, hearths, and tools survived in a bog. The site helped show that people were in South America before the Clovis culture.",
    "Approximate. The occupation is widely dated to about 14,500 years ago.",
)
add(
    "clovis",
    "Clovis culture",
    "history",
    -11000,
    -10800,
    32.00,
    -102.00,
    "North American plains",
    "North America",
    "Clovis spear points, fluted and very widespread, date to about 13,000 years ago. They mark a famous early culture of North America, not the first people there. The culture lasted only a few centuries.",
    "Approximate. Clovis is widely dated to about 13,050–12,750 years ago.",
)
add(
    "poverty-point",
    "Poverty Point",
    "history",
    -1700,
    -1100,
    32.64,
    -91.41,
    "Poverty Point, Louisiana",
    "North America",
    "Poverty Point is a set of enormous earth ridges built by hunter-gatherers in the lower Mississippi valley. The main earthworks are widely dated to about 1700–1100 BCE. People there traded stone from hundreds of kilometres away.",
    "Approximate. The earthworks are widely dated to about 1700–1100 BCE.",
)
add(
    "olmec",
    "Olmec centres",
    "history",
    -1200,
    -400,
    17.80,
    -94.20,
    "San Lorenzo, Mexico",
    "North America",
    "San Lorenzo and later La Venta were centres of the Olmec tradition, famous for colossal stone heads. San Lorenzo's peak is widely dated to about 1200–900 BCE. Olmec art and ritual influenced later Mesoamerican societies.",
    "Approximate. San Lorenzo flourished from about 1200 BCE.",
)
add(
    "caral",
    "City of Caral",
    "history",
    -3000,
    -1800,
    -10.89,
    -77.52,
    "Caral, Peru",
    "South America",
    "Caral, in the Supe Valley, is the oldest known city in the Americas, with plazas and pyramids. It flourished from about 3000 to 1800 BCE. The people farmed and fished, and they built on a monumental scale without pottery.",
    "Approximate. Caral is widely dated to about 3000–1800 BCE.",
)
add(
    "chavin",
    "Chavín de Huántar",
    "history",
    -900,
    -200,
    -9.59,
    -77.18,
    "Chavín de Huántar, Peru",
    "South America",
    "Chavín de Huántar was a ceremonial centre in the Andes whose art spread widely. Its main temple phase is dated to about 900–200 BCE. A gallery inside the temple holds the Lanzón, a carved granite figure.",
    "Approximate. The horizon style is widely dated to about 900–200 BCE.",
)
add(
    "maya-writing",
    "Early Maya writing",
    "history",
    -300,
    -100,
    17.22,
    -89.62,
    "Maya lowlands",
    "North America",
    "Maya writing is in evidence by the Late Preclassic, around the last centuries BCE. It became a full hieroglyphic script used for history, ritual, and astronomy. Later Classic cities such as Tikal recorded long sequences of kings.",
    "Approximate. Early Maya script is widely placed by about the third century BCE.",
)
add(
    "teotihuacan",
    "Teotihuacan",
    "history",
    100,
    550,
    19.69,
    -98.84,
    "Teotihuacan, Mexico",
    "North America",
    "Teotihuacan grew into one of the largest cities in the world, with the Pyramids of the Sun and Moon along a great avenue. Its height is widely dated from about 100 to 550. The city's violent burning in the sixth century ended its power.",
    "Approximate. The city's peak is widely dated to about 100–550.",
)
add(
    "moche",
    "Moche culture",
    "history",
    100,
    700,
    -8.11,
    -78.99,
    "Huacas del Sol y de la Luna, Peru",
    "South America",
    "The Moche of the north coast of Peru built adobe pyramids and made portrait vessels and fine metalwork. Their classic period is widely dated to about 100–700. Murals and pots show elaborate ceremonies, including sacrifice.",
    "Approximate. The Moche florescence is widely dated to about 100–700.",
)
add(
    "nazca-lines",
    "Nazca lines",
    "history",
    -200,
    600,
    -14.74,
    -75.13,
    "Nazca, Peru",
    "South America",
    "On the desert plain of Nazca, people scraped away dark stones to make huge figures and straight lines. Most of the geoglyphs are dated between about 200 BCE and 600 CE. They are best seen from above, though they were made and walked at ground level.",
    "Approximate. The lines are widely dated from about 200 BCE to 600 CE.",
)
add(
    "copan-dynasty",
    "Yax K'uk' Mo' at Copán",
    "history",
    426,
    426,
    14.84,
    -89.14,
    "Copán, Honduras",
    "North America",
    "In 426 a ruler named Yax K'uk' Mo' founded the Classic dynasty of Copán, according to later inscriptions. The city became a major Maya centre of sculpture and astronomy. Its dated monuments run for centuries after that founding.",
    "The inscriptions date the founding to 426.",
)
add(
    "tiwanaku",
    "Tiwanaku",
    "history",
    500,
    1000,
    -16.55,
    -68.67,
    "Tiwanaku, Bolivia",
    "South America",
    "Tiwanaku, near Lake Titicaca, was the ceremonial capital of a highland state. Its monumental core flourished from about 500 to 1000. The Gateway of the Sun and huge stone blocks still stand on the site.",
    "Approximate. The monumental city is widely dated to about 500–1000.",
)
add(
    "cahokia",
    "Cahokia",
    "history",
    1050,
    1200,
    38.66,
    -90.06,
    "Cahokia, Illinois",
    "North America",
    "Around 1050, Cahokia near the Mississippi became the largest city north of Mexico, centred on Monks Mound. Its peak lasted into the twelfth century. The people, often linked to the Mississippian tradition, farmed maize and built plazas and mounds.",
    "Approximate. The city's sudden growth is widely dated to about 1050.",
)
add(
    "chaco",
    "Chaco Canyon",
    "history",
    850,
    1150,
    36.06,
    -107.96,
    "Chaco Canyon, New Mexico",
    "North America",
    "In Chaco Canyon, Ancestral Puebloans built great houses such as Pueblo Bonito and a network of roads. The classic period is widely dated to about 850–1150. The canyon was a ceremonial centre for a wide region of the Southwest.",
    "Approximate. The great-house era is widely dated to about 850–1150.",
)
add(
    "thule-migration",
    "Thule migration",
    "history",
    1000,
    1300,
    69.00,
    -105.00,
    "Arctic North America",
    "North America",
    "Thule people, ancestors of the Inuit, spread east from Alaska across the Canadian Arctic to Greenland around 1000–1300. They used dog sleds, umiaks, and toggling harpoons. They replaced or absorbed the earlier Dorset tradition.",
    "Approximate. The eastward spread is widely dated to about 1000–1300.",
)
add(
    "tenochtitlan",
    "Foundation of Tenochtitlan",
    "history",
    1325,
    1325,
    19.43,
    -99.13,
    "Tenochtitlan, Mexico",
    "North America",
    "Mexica tradition dates the founding of Tenochtitlan, on islands in Lake Texcoco, to 1325. The city became the capital of the Aztec Empire. Spanish forces and indigenous allies destroyed it in 1521.",
    "The traditional foundation date is 1325.",
)
add(
    "inca-expansion",
    "Inca expansion",
    "history",
    1438,
    1532,
    -13.52,
    -71.98,
    "Cusco, Peru",
    "South America",
    "From the reign of Pachacuti, traditionally beginning in 1438, the Inca state expanded from Cusco into the largest empire of the Americas. It built roads, storehouses, and the estate of Machu Picchu. Spanish forces captured the emperor Atahualpa in 1532.",
    "Pachacuti's reign is traditionally dated from 1438. Atahualpa was captured in 1532.",
)
add(
    "columbus-1492",
    "Columbus reaches the Caribbean",
    "history",
    1492,
    1492,
    24.00,
    -74.50,
    "The Bahamas",
    "North America",
    "On 12 October 1492 a Spanish expedition led by Christopher Columbus landed in the Bahamas, after crossing the Atlantic from Palos. He thought he was near Asia. The voyage began sustained European colonisation of the Americas, with catastrophic consequences for indigenous peoples.",
    "Landfall was on 12 October 1492.",
    path=[
        (37.23, -6.89),
        (28.0, -16.0),
        (24.0, -74.5),
    ],
)
add(
    "cabral-brazil",
    "Cabral reaches Brazil",
    "history",
    1500,
    1500,
    -16.35,
    -39.05,
    "Porto Seguro, Brazil",
    "South America",
    "On 22 April 1500 a Portuguese fleet under Pedro Álvares Cabral sighted the coast of Brazil. Portugal then claimed the land under the Treaty of Tordesillas. The landing began Portuguese colonisation of South America.",
    "The landfall is dated to 22 April 1500.",
)
add(
    "cortes",
    "Fall of Tenochtitlan",
    "history",
    1519,
    1521,
    19.43,
    -99.13,
    "Tenochtitlan, Mexico",
    "North America",
    "Hernán Cortés landed on the Mexican coast in 1519 and, with many indigenous allies, reached Tenochtitlan. Disease, siege, and war destroyed the Aztec capital in 1521. Spanish colonial rule of central Mexico followed.",
    "Cortés landed in 1519. Tenochtitlan fell on 13 August 1521.",
)
add(
    "pizarro",
    "Spanish capture of the Inca emperor",
    "history",
    1532,
    1533,
    -6.70,
    -79.45,
    "Cajamarca, Peru",
    "South America",
    "In November 1532 Francisco Pizarro's small force seized the Inca emperor Atahualpa at Cajamarca. Atahualpa was killed in 1533 after a huge ransom in gold and silver. Spanish rule then spread through the Andes.",
    "Atahualpa was seized on 16 November 1532 and killed in 1533.",
)
add(
    "potosi",
    "Silver of Potosí",
    "history",
    1545,
    1545,
    -19.59,
    -65.75,
    "Potosí, Bolivia",
    "South America",
    "Silver was found at Potosí in 1545, and the mountain became the richest mine of the Spanish Empire. Forced and wage labour, including the mita draft, pulled indigenous people into deadly work. American silver reshaped prices from Seville to China.",
    "The discovery is dated to 1545.",
)
add(
    "atlantic-slave-trade",
    "Atlantic slave trade",
    "history",
    1518,
    1866,
    5.08,
    -1.35,
    "Elmina, Ghana",
    "Africa",
    "From the sixteenth century into the nineteenth, European ships carried enslaved Africans across the Atlantic to the Americas. The Trans-Atlantic Slave Trade Database records about 12.5 million people forced onto ships. The trade enriched European and American ports and devastated societies in Africa.",
    "Approximate. A direct trade to the Spanish Caribbean was licensed in 1518, and voyages continued into the 1860s.",
)
add(
    "pueblo-revolt",
    "Pueblo Revolt",
    "history",
    1680,
    1680,
    35.69,
    -105.94,
    "Santa Fe, New Mexico",
    "North America",
    "In 1680 Pueblo communities led by Popé drove Spanish colonists out of New Mexico. The revolt answered forced labour and the suppression of Pueblo religion. Spain reconquered the region in the 1690s.",
    "The revolt began on 10 August 1680.",
)
add(
    "haitian-revolution",
    "Haitian Revolution",
    "history",
    1791,
    1804,
    19.76,
    -72.20,
    "Saint-Domingue, Haiti",
    "North America",
    "Enslaved people in the French colony of Saint-Domingue rose in 1791. Under leaders including Toussaint Louverture and Jean-Jacques Dessalines, they defeated French, Spanish, and British forces. Haiti declared independence on 1 January 1804, the first state born of a successful revolt of enslaved people.",
    "The revolt began in August 1791. Independence was declared on 1 January 1804.",
)
add(
    "tupac-amaru",
    "Rebellion of Túpac Amaru II",
    "history",
    1780,
    1781,
    -13.52,
    -71.98,
    "Cusco, Peru",
    "South America",
    "In 1780 José Gabriel Condorcanqui, called Túpac Amaru II, led a great Andean rebellion against Spanish officials. The rising spread through the southern Andes and was crushed in 1781. He was executed in Cusco.",
    "The rebellion is dated from November 1780 to 1781.",
)
add(
    "ayacucho",
    "Battle of Ayacucho",
    "history",
    1824,
    1824,
    -13.16,
    -74.22,
    "Ayacucho, Peru",
    "South America",
    "On 9 December 1824 a patriot army under Antonio José de Sucre defeated the last large Spanish force in Peru at Ayacucho. The battle ended Spanish rule on the South American mainland. Bolívar's campaigns had prepared the victory.",
    "The battle was fought on 9 December 1824.",
)
add(
    "brazil-independence",
    "Independence of Brazil",
    "history",
    1822,
    1822,
    -23.55,
    -46.63,
    "São Paulo, Brazil",
    "South America",
    "On 7 September 1822 Prince Pedro declared Brazil independent of Portugal on the banks of the Ipiranga. He became emperor Pedro I. Brazil, unlike most of Spanish America, remained a monarchy for the rest of the century.",
    "Independence was declared on 7 September 1822.",
)
add(
    "trail-of-tears",
    "Indian Removal",
    "history",
    1830,
    1838,
    35.47,
    -84.00,
    "Cherokee country to Indian Territory",
    "North America",
    "The United States Indian Removal Act of 1830 authorised the expulsion of eastern nations to lands west of the Mississippi. In 1838 the army forced the Cherokee west on a journey remembered as the Trail of Tears. Thousands died on the removals.",
    "The Act is dated 1830. The Cherokee removal was in 1838.",
)
add(
    "sequoyah",
    "Cherokee syllabary",
    "history",
    1821,
    1821,
    35.50,
    -84.90,
    "Cherokee Nation",
    "North America",
    "Sequoyah completed a syllabary for the Cherokee language in 1821, and it was quickly adopted. Within a few years Cherokee people were printing books and a newspaper in their own script. It is a rare case of a writing system invented by one person and taken up by a nation.",
    "The syllabary was completed in 1821.",
)
add(
    "mexican-independence",
    "Independence of Mexico",
    "history",
    1821,
    1821,
    19.43,
    -99.13,
    "Mexico City",
    "North America",
    "After a war that began with Miguel Hidalgo's call in 1810, Mexico won independence in 1821 under the Plan of Iguala. Agustín de Iturbide entered Mexico City in September. Spain's three-century viceroyalty of New Spain was over.",
    "The Army of the Three Guarantees entered Mexico City on 27 September 1821.",
)
add(
    "us-civil-war",
    "United States Civil War",
    "history",
    1861,
    1865,
    38.90,
    -77.04,
    "United States",
    "North America",
    "Eleven southern states seceded in 1860–1861 to protect slavery, and war followed until 1865. The Union victory ended legal slavery through the Thirteenth Amendment. About 750,000 soldiers died, and the Reconstruction that followed was bitterly contested.",
    "The war is dated from April 1861 to April 1865. The Thirteenth Amendment was ratified in December 1865.",
)
add(
    "canadian-confederation",
    "Canadian Confederation",
    "history",
    1867,
    1867,
    45.42,
    -75.70,
    "Ottawa, Canada",
    "North America",
    "On 1 July 1867 the British North America Act joined Ontario, Quebec, Nova Scotia, and New Brunswick as the Dominion of Canada. Other provinces and territories entered later. Indigenous nations were not partners to the Act.",
    "Confederation took effect on 1 July 1867.",
)
add(
    "war-of-the-pacific",
    "War of the Pacific",
    "history",
    1879,
    1884,
    -23.65,
    -70.40,
    "Atacama and the Pacific coast",
    "South America",
    "Chile fought Bolivia and Peru from 1879 to 1884 over the nitrate deserts of the Atacama. Chile won and took territories that left Bolivia landlocked. The war still shapes relations among the three countries.",
    "The war is dated from 1879 to the Treaty of Ancón's aftermath in 1884.",
)
add(
    "brazilian-abolition",
    "Abolition in Brazil",
    "history",
    1888,
    1888,
    -22.90,
    -43.17,
    "Rio de Janeiro, Brazil",
    "South America",
    "The Golden Law of 13 May 1888 abolished slavery in Brazil, the last country in the Americas to do so. Princess Isabel signed it in the absence of the emperor. The monarchy itself fell the next year.",
    "The Golden Law was signed on 13 May 1888.",
)
add(
    "mexican-revolution",
    "Mexican Revolution",
    "history",
    1910,
    1920,
    19.43,
    -99.13,
    "Mexico",
    "North America",
    "In 1910 Francisco Madero challenged the long rule of Porfirio Díaz, and the country slid into revolution. Leaders including Emiliano Zapata and Pancho Villa fought over land and power. A new constitution in 1917, and the end of major fighting around 1920, reshaped the state.",
    "The revolution is dated from 1910. The constitution is of 1917.",
)
add(
    "panama-canal",
    "Panama Canal",
    "history",
    1914,
    1914,
    9.08,
    -79.68,
    "Panama",
    "North America",
    "The Panama Canal opened to shipping on 15 August 1914, linking the Atlantic and Pacific. The United States had backed Panama's separation from Colombia in 1903 and then built the canal. Thousands of workers, many from the Caribbean, died during construction.",
    "The canal opened on 15 August 1914.",
)
add(
    "tulsa",
    "Tulsa massacre",
    "history",
    1921,
    1921,
    36.16,
    -95.99,
    "Tulsa, Oklahoma",
    "North America",
    "On 31 May and 1 June 1921 a white mob destroyed the Black district of Greenwood in Tulsa. Hundreds of people were killed and thousands were left homeless. The attack was long minimised in official accounts.",
    "The massacre was on 31 May–1 June 1921.",
)
add(
    "dust-bowl",
    "Dust Bowl",
    "history",
    1930,
    1940,
    36.70,
    -100.50,
    "Southern Great Plains",
    "North America",
    "In the 1930s drought and ploughing turned the southern plains of the United States into the Dust Bowl. Huge storms stripped the soil, and many farm families left. The crisis coincided with the Great Depression.",
    "The worst dust storms are dated to the 1930s.",
)
add(
    "new-deal",
    "New Deal",
    "history",
    1933,
    1938,
    38.90,
    -77.04,
    "Washington, D.C.",
    "North America",
    "After taking office in 1933, Franklin Roosevelt launched the New Deal, a set of relief, recovery, and reform programmes. It included public works, banking reform, and Social Security. It did not end the Depression by itself, but it remade the federal government.",
    "Roosevelt took office on 4 March 1933. Major New Deal laws followed through the 1930s.",
)
add(
    "cuban-revolution",
    "Cuban Revolution",
    "history",
    1959,
    1959,
    23.14,
    -82.36,
    "Havana, Cuba",
    "North America",
    "On 1 January 1959 Fidel Castro's rebel movement took power in Cuba after the flight of Fulgencio Batista. The new government broke with the United States and aligned with the Soviet Union. The revolution reshaped the Caribbean and the Cold War.",
    "Batista fled on 1 January 1959.",
)
add(
    "civil-rights-act",
    "Civil Rights Act",
    "history",
    1964,
    1964,
    38.90,
    -77.04,
    "Washington, D.C.",
    "North America",
    "The Civil Rights Act of 1964 outlawed segregation in public places and discrimination in employment in the United States. It followed the March on Washington in 1963 and years of Black organising. President Lyndon Johnson signed it on 2 July 1964.",
    "The Act was signed on 2 July 1964.",
)
add(
    "apollo-11",
    "Apollo 11",
    "history",
    1969,
    1969,
    28.61,
    -80.60,
    "Kennedy Space Center, Florida",
    "North America",
    "Apollo 11 launched from Florida on 16 July 1969, and on 20 July Neil Armstrong and Buzz Aldrin walked on the Moon. Michael Collins stayed in orbit. It was the first time people landed on another world.",
    "Launch was on 16 July 1969. The landing was on 20 July 1969.",
)
add(
    "allende",
    "Coup in Chile",
    "history",
    1973,
    1973,
    -33.45,
    -70.67,
    "Santiago, Chile",
    "South America",
    "On 11 September 1973 the Chilean armed forces overthrew President Salvador Allende, who died in the presidential palace. General Augusto Pinochet then ruled as a dictator until 1990. Thousands of people were killed or tortured.",
    "The coup was on 11 September 1973.",
)
add(
    "mothers-plaza",
    "Mothers of the Plaza de Mayo",
    "history",
    1977,
    1977,
    -34.61,
    -58.37,
    "Buenos Aires, Argentina",
    "South America",
    "From April 1977 mothers of people kidnapped by Argentina's military dictatorship marched each week in the Plaza de Mayo. They demanded to know where their children were. The marches became the most visible protest against the junta.",
    "The first march was on 30 April 1977.",
)
add(
    "chile-plebiscite",
    "Chilean plebiscite",
    "history",
    1988,
    1988,
    -33.45,
    -70.67,
    "Santiago, Chile",
    "South America",
    "On 5 October 1988 Chileans voted No to another term for Augusto Pinochet. The vote, which the regime had expected to win, opened the way to elections. Pinochet left the presidency in 1990.",
    "The plebiscite was on 5 October 1988.",
)
add(
    "colombia-peace",
    "Colombian peace agreement",
    "history",
    2016,
    2016,
    4.71,
    -74.07,
    "Bogotá, Colombia",
    "South America",
    "In 2016 the Colombian government and the FARC guerrilla army signed a peace agreement ending a war that had lasted more than fifty years. A first text was narrowly rejected in a referendum, and a revised accord was then approved by Congress. The conflict had killed hundreds of thousands of people.",
    "The final agreement was signed on 24 November 2016.",
)
add(
    "trc-canada",
    "Truth and Reconciliation Commission of Canada",
    "history",
    2015,
    2015,
    45.42,
    -75.70,
    "Ottawa, Canada",
    "North America",
    "In 2015 Canada's Truth and Reconciliation Commission reported on residential schools, which had removed indigenous children from their families for more than a century. The commission called the system a cultural genocide. Its calls to action remain a reference point in Canadian politics.",
    "The final report was released on 15 December 2015.",
)
add(
    "popol-vuh",
    "Popol Vuh",
    "myth",
    1550,
    1558,
    15.00,
    -91.15,
    "K'iche' highlands, Guatemala",
    "North America",
    "The Popol Vuh tells how the Hero Twins defeated the lords of the underworld, and how the K'iche' people were created. It is the great written myth of the K'iche' Maya. The alphabetic text was set down in the 1550s, from an older tradition, and later copied by the friar Francisco Ximénez.",
    "Earliest written source. The alphabetic Popol Vuh was written in the 1550s. The tradition is older.",
)
add(
    "fifth-sun",
    "The Fifth Sun",
    "myth",
    1550,
    1570,
    19.43,
    -99.13,
    "Tenochtitlan, Mexico",
    "North America",
    "Aztec tradition held that the present world is the Fifth Sun, made when gods sacrificed themselves at Teotihuacan. The story was painted in pre-Hispanic books and written in Spanish and Nahuatl after the conquest. The fullest alphabetic accounts date to the mid-sixteenth century.",
    "Earliest written source. Alphabetic accounts were written in the mid-sixteenth century. Painted books are older, and their exact years are not fixed.",
)
add(
    "quetzalcoatl",
    "Quetzalcoatl",
    "myth",
    1550,
    1580,
    20.06,
    -99.34,
    "Tula, Mexico",
    "North America",
    "Quetzalcoatl, the feathered serpent, is a major sacred figure of Mesoamerica, linked both to a god and to stories of a priest-king of Tollan. There is no single agreed historical year for those stories. They were written down in Spanish and Nahuatl chronicles of the sixteenth century, and they appear in earlier art.",
    "Earliest written source. The narrative was written in sixteenth-century chronicles. Images of the feathered serpent are much older.",
)
add(
    "viracocha",
    "Viracocha",
    "myth",
    1550,
    1572,
    -13.52,
    -71.98,
    "Cusco, Peru",
    "South America",
    "Inca tradition told of Viracocha, a creator who travelled the world and of the first ancestors who emerged near Cusco. Spanish chroniclers wrote these stories down in the sixteenth century. There is no traditional calendar year that historians treat as a date for the creation itself.",
    "Earliest written source. Spanish chronicles of the mid-sixteenth century are the earliest full texts. The tradition is older.",
)
add(
    "el-dorado",
    "El Dorado",
    "myth",
    1530,
    1590,
    5.15,
    -73.67,
    "Lake Guatavita, Colombia",
    "South America",
    "Spanish writers turned reports of a Muisca ritual, in which a ruler covered in gold dust offered treasure to Lake Guatavita, into the legend of a golden kingdom. The written legend is a sixteenth-century European story about an American rite. Expeditions spent decades looking for a city that was not there.",
    "Earliest written source. Spanish accounts of the gilded king were written in the sixteenth century.",
)
add(
    "raven-steals-sun",
    "Raven releases the light",
    "myth",
    1890,
    1910,
    53.25,
    -132.00,
    "Haida Gwaii, Canada",
    "North America",
    "Haida, Tlingit, and other Northwest Coast traditions tell how Raven stole the sun, moon, and stars from a box and released them. The stories were oral long before anyone wrote them down. Substantial written versions were recorded by ethnographers around the end of the nineteenth century.",
    "Earliest written source. Extended written versions were recorded around 1890–1910. The oral tradition is older.",
)
add(
    "muisca-raft",
    "Muisca gold raft",
    "history",
    600,
    1600,
    5.15,
    -73.67,
    "Lake Guatavita, Colombia",
    "South America",
    "Muisca communities around the high lakes of Colombia made gold offerings, including the famous gold raft now in Bogotá. The ritual tradition is dated to the centuries before the Spanish conquest. Spanish observers later turned one ceremony into the legend of El Dorado.",
    "Approximate. Muisca goldwork and lake offerings are dated to the late pre-Hispanic centuries.",
)
add(
    "haitian-constitution",
    "Haitian constitution of 1805",
    "history",
    1805,
    1805,
    19.76,
    -72.20,
    "Haiti",
    "North America",
    "In 1805 independent Haiti adopted a constitution under Jean-Jacques Dessalines. It abolished slavery and claimed the land for all Haitians. The document followed the declaration of independence of 1804.",
    "The constitution is dated 20 May 1805.",
)
add(
    "war-triple-alliance",
    "War of the Triple Alliance",
    "history",
    1864,
    1870,
    -25.30,
    -57.64,
    "Paraguay",
    "South America",
    "From 1864 to 1870 Paraguay fought Brazil, Argentina, and Uruguay. The war killed a huge part of Paraguay's population, though exact figures are disputed. It remains the most destructive interstate war in South American history.",
    "The war is dated from 1864 to 1870.",
)
add(
    "rubber-manaus",
    "Amazon rubber boom",
    "history",
    1880,
    1912,
    -3.12,
    -60.02,
    "Manaus, Brazil",
    "South America",
    "From about 1880 to 1912 a boom in wild rubber made Manaus rich and pulled indigenous people into violent labour across the Amazon. The opera house in Manaus is a monument of that boom. Plantations in Asia then undercut the trade.",
    "Approximate. The boom is widely dated from about 1880 to 1912.",
)
add(
    "falklands-war",
    "Falklands War",
    "history",
    1982,
    1982,
    -51.70,
    -57.85,
    "Falkland Islands",
    "South America",
    "In April 1982 Argentina seized the Falkland Islands, which it calls the Malvinas and which Britain had long administered. Britain retook the islands in a war that ended in June. The sovereignty dispute was not settled.",
    "Argentine forces landed on 2 April 1982. Fighting ended on 14 June 1982.",
)
add(
    "stonewall",
    "Stonewall uprising",
    "history",
    1969,
    1969,
    40.73,
    -74.00,
    "New York, United States",
    "North America",
    "On 28 June 1969 patrons of the Stonewall Inn in New York resisted a police raid. Several nights of protest followed. The uprising became a symbol of the movement for gay and transgender rights.",
    "The raid was on 28 June 1969.",
)
add(
    "september-11",
    "Attacks of 11 September 2001",
    "history",
    2001,
    2001,
    40.71,
    -74.01,
    "New York, United States",
    "North America",
    "On 11 September 2001 hijackers flew airliners into the World Trade Center and the Pentagon, and a fourth plane crashed in Pennsylvania. Nearly three thousand people were killed. The attacks began a long war led by the United States.",
    "The attacks were on 11 September 2001.",
)
add(
    "obama-election",
    "Election of Barack Obama",
    "history",
    2008,
    2008,
    41.88,
    -87.62,
    "Chicago, United States",
    "North America",
    "In November 2008 Barack Obama was elected president of the United States, the first Black person to hold the office. He took office in January 2009 during a global financial crisis. His election did not end racial inequality.",
    "The election was on 4 November 2008.",
)
add(
    "wari-empire",
    "Wari Empire",
    "history",
    600,
    1000,
    -13.06,
    -74.20,
    "Ayacucho, Peru",
    "South America",
    "The Wari state, based near Ayacucho, built planned compounds across much of Peru. It flourished from about 600 to 1000, alongside Tiwanaku in the south. Its collapse left the highlands divided before the Inca expansion.",
    "Approximate. Wari is widely dated to about 600–1000.",
)
