from lib import add

add(
    "qesem-fire",
    "Hearths at Qesem Cave",
    "history",
    -300000,
    -200000,
    32.11,
    34.98,
    "Qesem Cave, Israel",
    "Asia",
    "Qesem Cave has repeated hearths and butchered animal bones from the later Middle Pleistocene. The cave's deposits begin earlier than 300,000 years ago and continue to about 200,000 years ago. They are widely cited as evidence of habitual fire use by early humans in the Levant.",
    "Approximate. The later hearths fall between about 300,000 and 200,000 years ago.",
)
add(
    "qafzeh-skhul",
    "Early humans at Skhul and Qafzeh",
    "history",
    -120000,
    -90000,
    32.68,
    35.30,
    "Qafzeh, Israel",
    "Asia",
    "Burials at Skhul and Qafzeh show Homo sapiens in the Levant about 120,000 to 90,000 years ago. This early presence outside Africa may not have lasted. A later dispersal, after about 70,000 years ago, is the one that peopled the rest of the world.",
    "Approximate. The burials are widely dated to about 120,000–90,000 years ago.",
)
add(
    "toba-eruption",
    "Toba eruption",
    "history",
    -74000,
    -74000,
    2.68,
    98.88,
    "Lake Toba, Sumatra, Indonesia",
    "Asia",
    "The Toba supervolcano in Sumatra erupted about 74,000 years ago, the largest known eruption of the last two million years. Ash from it is found across South Asia. Claims that it almost wiped out humanity are now widely doubted.",
    "Approximate. The eruption is widely dated to about 74,000 years ago.",
)
add(
    "denisova-cave",
    "Denisovans of the Altai",
    "history",
    -100000,
    -50000,
    51.40,
    84.68,
    "Denisova Cave, Russia",
    "Asia",
    "A finger bone and teeth from Denisova Cave belonged to a population now called Denisovans, known mainly from ancient DNA. Fossils from the cave span a broad period around 100,000 to 50,000 years ago, and individual dates still differ. People today in Island Southeast Asia and Oceania carry some Denisovan ancestry.",
    "Approximate. The cave's Denisovan fossils fall broadly between about 100,000 and 50,000 years ago.",
)
add(
    "homo-floresiensis",
    "Homo floresiensis",
    "history",
    -100000,
    -60000,
    -8.53,
    120.27,
    "Liang Bua, Flores, Indonesia",
    "Asia",
    "Remains of a small-bodied hominin, nicknamed the hobbit, were found at Liang Bua on Flores. Revised dating places the bones at about 100,000 to 60,000 years ago, not in the last 12,000 years as first reported. The species shows that several kinds of human lived in Island Southeast Asia.",
    "Approximate. The revised chronology places the bones at about 100,000–60,000 years ago.",
)
add(
    "sulawesi-cave-art",
    "Cave painting in Sulawesi",
    "history",
    -45500,
    -45500,
    -5.00,
    119.70,
    "Leang Tedongnge, Sulawesi, Indonesia",
    "Asia",
    "A painting of a warty pig at Leang Tedongnge is dated to at least 45,500 years ago. It is among the oldest known figurative art in the world. Nearby caves in Maros-Pangkep have other paintings of a similar age.",
    "Approximate. The pig painting is dated to at least about 45,500 years ago.",
)
add(
    "jomon-pottery",
    "Jōmon pottery",
    "history",
    -14000,
    -10000,
    36.06,
    140.12,
    "Japan",
    "Asia",
    "Pottery of the Incipient Jōmon tradition is among the oldest known anywhere. Early vessels are widely dated to about 14,000 BCE, with dates varying by site. Hunter-gatherers in the Japanese archipelago made and used them long before farming.",
    "Approximate. The earliest Jōmon pots are widely placed around 14,000 BCE.",
)
add(
    "gobekli-tepe",
    "Göbekli Tepe",
    "history",
    -9600,
    -8200,
    37.22,
    38.92,
    "Göbekli Tepe, Turkey",
    "Asia",
    "At Göbekli Tepe, hunter-gatherers raised T-shaped stone pillars carved with animals. The enclosures are widely dated to about 9600–8200 BCE, before pottery and before settled farming villages in the region. The site was later deliberately buried.",
    "Approximate. The main enclosures are widely dated to about 9600–8200 BCE.",
)
add(
    "jericho-tower",
    "Tower of Jericho",
    "history",
    -8000,
    -7500,
    31.87,
    35.44,
    "Tell es-Sultan, Jericho",
    "Asia",
    "A stone tower and wall at Tell es-Sultan belong to the Pre-Pottery Neolithic, around the eighth millennium BCE. Jericho is one of the longest-lived settlement mounds in the world. The tower is older than the pottery and cities of later ages.",
    "Approximate. The tower is widely dated to the eighth millennium BCE.",
)
add(
    "catalhoyuk",
    "Çatalhöyük",
    "history",
    -7100,
    -6000,
    37.67,
    32.83,
    "Çatalhöyük, Turkey",
    "Asia",
    "Çatalhöyük was a dense settlement of mud-brick houses entered from the roof. It was occupied from about 7100 to 6000 BCE. Wall paintings and burials under the floors show a rich ritual life.",
    "Approximate. The main occupation is widely dated to about 7100–6000 BCE.",
)
add(
    "yangtze-rice",
    "Rice cultivation on the Yangtze",
    "history",
    -7000,
    -5000,
    29.40,
    112.20,
    "Middle Yangtze, China",
    "Asia",
    "People in the Yangtze basin domesticated rice over several thousand years. Early cultivated rice is widely in place by about 7000–5000 BCE. It later became the staple of much of East and Southeast Asia.",
    "Approximate. Early rice cultivation is widely placed by about 7000–5000 BCE.",
)
add(
    "mehrgarh",
    "Mehrgarh",
    "history",
    -7000,
    -5000,
    29.40,
    67.60,
    "Mehrgarh, Pakistan",
    "Asia",
    "Mehrgarh, at the foot of the Bolan Pass, has some of the earliest farming and herding in South Asia. The first occupation is widely dated to about 7000 BCE. Later levels lead toward the Indus cities.",
    "Approximate. The early farming levels are widely dated from about 7000 BCE.",
)
add(
    "indus-cities",
    "Indus cities",
    "history",
    -2600,
    -1900,
    27.33,
    68.14,
    "Mohenjo-daro, Pakistan",
    "Asia",
    "From about 2600 to 1900 BCE, cities such as Mohenjo-daro and Harappa shared weights, seals, and planned streets across the Indus basin. Their script is still undeciphered. The cities were largely abandoned after about 1900 BCE.",
    "Approximate. The mature Indus phase is widely dated to about 2600–1900 BCE.",
)
add(
    "sargon-akkad",
    "Empire of Akkad",
    "history",
    -2334,
    -2154,
    33.10,
    44.10,
    "Akkad, Mesopotamia",
    "Asia",
    "Sargon of Akkad built a state that joined the cities of Mesopotamia in the twenty-fourth century BCE. Later tradition gave him a long reign, and the exact years are approximate. The empire fell in the twenty-second century BCE.",
    "Approximate. Sargon's reign is widely placed in the 24th century BCE.",
)
add(
    "hammurabi",
    "Laws of Hammurabi",
    "history",
    -1750,
    -1750,
    32.54,
    44.42,
    "Babylon, Iraq",
    "Asia",
    "Hammurabi, king of Babylon, set up a diorite stele of laws in the eighteenth century BCE. The prologue and epilogue frame a long list of judgments. It is one of the earliest extensive law codes to survive.",
    "Approximate. The stele is widely dated to Hammurabi's reign, around 1750 BCE.",
)
add(
    "hittite-hattusa",
    "Hittite capital at Hattusa",
    "history",
    -1650,
    -1180,
    40.02,
    34.62,
    "Hattusa, Turkey",
    "Asia",
    "Hattusa was the capital of the Hittite kingdom, a great power of the Late Bronze Age. The city and the archives of cuneiform tablets were abandoned around 1180 BCE, during the wider Bronze Age collapse. The texts include treaties and royal annals.",
    "Approximate. Hattusa was a capital from about 1650 BCE until about 1180 BCE.",
)
add(
    "shang-oracle-bones",
    "Oracle bones of Anyang",
    "history",
    -1250,
    -1046,
    36.12,
    114.32,
    "Yinxu, Anyang, China",
    "Asia",
    "At Yinxu, the late Shang capital, kings recorded divinations on cattle bone and turtle shell. These oracle bones, from about 1250 to 1046 BCE, are the earliest substantial Chinese writing. They name royal ancestors and military campaigns.",
    "Approximate. The Anyang oracle bones are widely dated to about 1250–1046 BCE.",
)
add(
    "bronze-age-collapse",
    "Bronze Age collapse",
    "history",
    -1200,
    -1150,
    34.76,
    36.00,
    "Eastern Mediterranean",
    "Asia",
    "Around 1200–1150 BCE, palace societies from Greece to the Levant were destroyed or shrank. Ugarit, the Hittite kingdom, and Mycenaean centres fell within a few decades. The causes are still debated, and Egyptian texts mention groups they called the Sea Peoples.",
    "Approximate. The main destructions cluster around 1200–1150 BCE.",
)
add(
    "zhou-conquest",
    "Zhou conquest of the Shang",
    "history",
    -1046,
    -1046,
    34.62,
    113.68,
    "Muye, China",
    "Asia",
    "The Zhou defeated the last Shang king at Muye and founded a new dynasty. The traditional date used by many historians is 1046 BCE, though other ancient chronologies differ by decades. The Zhou then ruled through a network of kin domains.",
    "Approximate. 1046 BCE is a widely used date, and ancient chronologies disagree.",
)
add(
    "phoenician-alphabet",
    "Phoenician alphabet",
    "history",
    -1050,
    -900,
    33.27,
    35.20,
    "Byblos, Lebanon",
    "Asia",
    "By about 1050 BCE, Phoenician cities were using a short alphabet of consonants. It is the ancestor of the Greek, Hebrew, Arabic, and Latin scripts. Early examples come from Byblos and other Levantine ports.",
    "Approximate. The script is widely in use by about the eleventh to tenth century BCE.",
)
add(
    "cyrus-babylon",
    "Cyrus takes Babylon",
    "history",
    -539,
    -539,
    32.54,
    44.42,
    "Babylon, Iraq",
    "Asia",
    "In 539 BCE Cyrus of Persia took Babylon, ending the Neo-Babylonian kingdom. The Cyrus Cylinder describes him as a restorer of temples and of displaced peoples. His empire then stretched from the Aegean to Central Asia.",
    "Babylon fell to Cyrus in 539 BCE.",
)
add(
    "confucius",
    "Confucius",
    "history",
    -551,
    -479,
    35.60,
    117.02,
    "Qufu, China",
    "Asia",
    "Kong Qiu, known in the West as Confucius, taught in the state of Lu in the sixth and fifth centuries BCE. The traditional dates of his life are 551–479 BCE. The Analects, a collection of his sayings, was compiled by later followers.",
    "The traditional dates are 551–479 BCE.",
)
add(
    "buddha",
    "The Buddha",
    "history",
    -480,
    -400,
    27.48,
    82.10,
    "Gangetic plain, India and Nepal",
    "Asia",
    "Siddhartha Gautama, the Buddha, taught a path out of suffering in the kingdoms of the central Ganges. Most historians place his life in the fifth or fourth century BCE. The traditional dates used in South Asia are earlier and are not agreed.",
    "Approximate. His life is widely placed in the fifth or fourth century BCE.",
)
add(
    "persepolis",
    "Persepolis",
    "history",
    -518,
    -330,
    29.93,
    52.89,
    "Persepolis, Iran",
    "Asia",
    "Darius I began the ceremonial capital of Persepolis in the late sixth century BCE. Reliefs there show delegations from across the Persian Empire bringing tribute. Alexander burned the palaces in 330 BCE.",
    "Construction began under Darius I around 518 BCE. Alexander burned the site in 330 BCE.",
)
add(
    "gaugamela",
    "Alexander at Gaugamela",
    "history",
    -331,
    -323,
    36.56,
    43.45,
    "Gaugamela, Iraq",
    "Asia",
    "In 331 BCE Alexander of Macedon defeated Darius III at Gaugamela and then took the Persian capitals. He died in Babylon in 323 BCE. His campaigns linked the eastern Mediterranean with Iran and the Indus.",
    "Gaugamela was fought on 1 October 331 BCE. Alexander died in 323 BCE.",
)
add(
    "ashoka-edicts",
    "Edicts of Ashoka",
    "history",
    -268,
    -232,
    25.01,
    85.42,
    "Patna, India",
    "Asia",
    "Ashoka, emperor of the Maurya realm, inscribed edicts on rocks and pillars across South Asia. They are widely dated to his reign, about 268–232 BCE, and some express remorse after the war in Kalinga. The edicts are the earliest extensive royal inscriptions of India.",
    "Approximate. Ashoka's reign is widely dated to about 268–232 BCE.",
)
add(
    "qin-unification",
    "Qin unification of China",
    "history",
    -221,
    -221,
    34.38,
    109.20,
    "Xianyang, China",
    "Asia",
    "In 221 BCE the king of Qin conquered the last rival state and took the title First Emperor. His government standardised script, weights, and axle widths. The dynasty fell in 206 BCE, soon after his death.",
    "Unification is dated to 221 BCE.",
)
add(
    "zhang-qian",
    "Zhang Qian's journey",
    "history",
    -139,
    -126,
    34.34,
    108.94,
    "Chang'an, China",
    "Asia",
    "The Han envoy Zhang Qian left Chang'an around 139 BCE, was held by the Xiongnu, and reached Central Asia before returning about 126 BCE. His report opened regular Han contact with the western regions. It is an early dated moment of the Silk Road.",
    "His mission is dated to about 139–126 BCE.",
)
add(
    "silk-road",
    "Silk Road",
    "history",
    -130,
    200,
    40.14,
    94.66,
    "Dunhuang, China",
    "Asia",
    "From the Han period into the early centuries CE, caravan routes linked China with Central Asia, Iran, and the Mediterranean. Silk, horses, glass, and ideas moved along them, and Dunhuang became a major gateway. The line is a schematic of the main land route, not a single road.",
    "Approximate. The classic land routes are well attested from the late second century BCE.",
    path=[
        (34.27, 108.94),
        (40.14, 94.66),
        (39.47, 75.99),
        (39.65, 66.96),
        (37.66, 62.18),
        (34.55, 38.27),
    ],
)
add(
    "cai-lun",
    "Paper reported to the Han court",
    "history",
    105,
    105,
    34.62,
    112.45,
    "Luoyang, China",
    "Asia",
    "In 105 CE the official Cai Lun presented an improved method of making paper to the Han emperor. Earlier plant-fibre sheets exist, so he did not invent paper from nothing. His process is the one later texts credit with spreading paper use.",
    "The court presentation is traditionally dated to 105 CE.",
)
add(
    "three-kingdoms",
    "Three Kingdoms",
    "history",
    220,
    280,
    30.57,
    114.30,
    "China",
    "Asia",
    "After the Han collapse, Wei, Shu, and Wu divided China from 220 until the Jin conquest of Wu in 280. The period is well dated in the dynastic histories. Later fiction, especially the Romance of the Three Kingdoms, added a great deal of legend.",
    "The kingdoms are dated from 220 to 280.",
)
add(
    "gupta-empire",
    "Gupta Empire",
    "history",
    320,
    550,
    25.32,
    83.00,
    "Pataliputra, India",
    "Asia",
    "Chandra Gupta I began the Gupta era in 320, and his successors ruled much of northern India. The period is associated with Sanskrit learning, temple building, and the mathematician Aryabhata. Hun invasions weakened the empire in the sixth century.",
    "The Gupta era begins in 320.",
)
add(
    "sassanid-empire",
    "Sassanid Empire",
    "history",
    224,
    651,
    30.00,
    52.40,
    "Istakhr and Ctesiphon",
    "Asia",
    "Ardashir I founded the Sassanid Empire in 224, and it remained the great power of Iran until the Arab conquest of 651. Its kings revived Zoroastrian state ritual and fought Rome and later Byzantium. The capital Ctesiphon stood on the Tigris.",
    "The dynasty is dated from 224 to the fall of Ctesiphon's realm in 651.",
)
add(
    "hijra",
    "Hijra",
    "history",
    622,
    622,
    24.47,
    39.61,
    "Medina, Saudi Arabia",
    "Asia",
    "In 622 Muhammad and his followers moved from Mecca to Yathrib, later called Medina. The journey, the Hijra, is year 1 of the Islamic calendar. From Medina the new community grew into a state.",
    "The Hijra is dated to 622.",
)
add(
    "battle-of-qadisiyyah",
    "Arab conquest of Sasanian Iraq",
    "history",
    636,
    651,
    31.58,
    44.50,
    "Qadisiyyah, Iraq",
    "Asia",
    "Arab Muslim armies defeated Sasanian forces at Qadisiyyah around 636 and took Ctesiphon. By 651 the last Sasanian king had been killed and Iran was under the new caliphate. The exact year of the battle is still discussed.",
    "Approximate. Qadisiyyah is widely placed in the mid-630s, and the Sasanian realm ended by 651.",
)
add(
    "baghdad-founded",
    "Foundation of Baghdad",
    "history",
    762,
    762,
    33.34,
    44.40,
    "Baghdad, Iraq",
    "Asia",
    "The Abbasid caliph al-Mansur founded Baghdad as his capital in 762, on a round plan beside the Tigris. The city became a centre of scholarship, including the translation of Greek and Persian works. It remained the Abbasid seat until the Mongol sack of 1258.",
    "Al-Mansur began the city in 762.",
)
add(
    "borobudur",
    "Borobudur",
    "history",
    780,
    830,
    -7.61,
    110.20,
    "Borobudur, Java, Indonesia",
    "Asia",
    "Borobudur is a vast Buddhist monument of terraces and bell-shaped stupas in central Java. It was built under the Sailendra dynasty around the late eighth and early ninth centuries. Reliefs around the galleries tell stories of the Buddha's former lives.",
    "Approximate. Construction is widely placed around 780–830.",
)
add(
    "angkor-802",
    "Foundation of Angkor",
    "history",
    802,
    802,
    13.41,
    103.87,
    "Angkor, Cambodia",
    "Asia",
    "In 802 Jayavarman II was consecrated as a universal ruler, a date later Cambodian tradition treats as the start of the Khmer Empire. Angkor grew into a huge complex of temples and reservoirs. The city remained a capital for centuries.",
    "The consecration is traditionally dated to 802.",
)
add(
    "heian-capital",
    "Heian capital",
    "history",
    794,
    794,
    35.01,
    135.77,
    "Kyoto, Japan",
    "Asia",
    "In 794 the Japanese court moved to Heian-kyō, today's Kyoto. The city stayed the imperial capital for more than a thousand years. The Heian period is also the age of The Tale of Genji, written around the year 1000.",
    "The court moved in 794.",
)
add(
    "tale-of-genji",
    "The Tale of Genji",
    "history",
    1008,
    1020,
    35.01,
    135.77,
    "Kyoto, Japan",
    "Asia",
    "Murasaki Shikibu wrote The Tale of Genji at the Heian court in the early eleventh century. It is often called the world's first novel. The exact years of composition are not known, but they fall in the 1000s.",
    "Approximate. The tale was written in the early eleventh century.",
)
add(
    "bi-sheng",
    "Movable type of Bi Sheng",
    "history",
    1040,
    1048,
    30.27,
    120.15,
    "China",
    "Asia",
    "The Song-dynasty craftsman Bi Sheng made movable type from fired clay in the 1040s. Shen Kuo described the method in his Dream Pool Essays of 1088. Later printers in Korea and China developed metal type.",
    "Approximate. Shen Kuo places Bi Sheng's work in the Qingli era, 1041–1048.",
)
add(
    "first-crusade",
    "First Crusade takes Jerusalem",
    "history",
    1099,
    1099,
    31.78,
    35.23,
    "Jerusalem",
    "Asia",
    "In July 1099 an army from western Europe captured Jerusalem after Pope Urban II's call to war in 1095. The attackers killed many of the city's Muslim and Jewish inhabitants. Crusader states then held parts of the Levant for generations.",
    "Jerusalem was taken on 15 July 1099.",
)
add(
    "gempei",
    "Genpei War",
    "history",
    1180,
    1185,
    34.30,
    135.60,
    "Japan",
    "Asia",
    "The Taira and Minamoto clans fought a civil war from 1180 to 1185. The Minamoto victory at Dan-no-ura ended Taira power. Minamoto no Yoritomo then established the Kamakura shogunate.",
    "The war is dated from 1180 to 1185.",
)
add(
    "delhi-sultanate",
    "Delhi Sultanate",
    "history",
    1206,
    1206,
    28.65,
    77.23,
    "Delhi, India",
    "Asia",
    "In 1206 Qutb al-Din Aibak, a former slave general, became ruler in Delhi and began the Delhi Sultanate. Muslim dynasties then ruled much of northern India for three centuries. The Qutb Minar still marks the early capital.",
    "Aibak's rule in Delhi is dated from 1206.",
)
add(
    "mongol-conquests",
    "Mongol conquests",
    "history",
    1206,
    1260,
    47.21,
    102.84,
    "Karakorum, Mongolia",
    "Asia",
    "Temüjin was proclaimed Chinggis Khan in 1206 and his armies then conquered northern China, Central Asia, Iran, and parts of eastern Europe. The western campaigns reached Hungary in 1241. The line is a schematic of that westward thrust, not every front.",
    "Chinggis Khan was acclaimed in 1206. The campaign into Hungary was in 1241, and the empire's unity frayed after 1259.",
    path=[
        (47.21, 102.84),
        (47.8, 91.0),
        (43.8, 87.6),
        (39.65, 66.96),
        (36.2, 58.8),
        (38.1, 46.3),
        (50.45, 30.52),
        (47.5, 19.0),
    ],
)
add(
    "baghdad-1258",
    "Sack of Baghdad",
    "history",
    1258,
    1258,
    33.34,
    44.40,
    "Baghdad, Iraq",
    "Asia",
    "In 1258 Hülegü's Mongol army took Baghdad and killed the Abbasid caliph. The city's libraries and canals were devastated. The sack ended the Abbasid caliphate as a political power in Iraq.",
    "Baghdad fell in February 1258.",
)
add(
    "kamikaze-1281",
    "Mongol invasions of Japan",
    "history",
    1274,
    1281,
    33.59,
    130.40,
    "Hakata Bay, Japan",
    "Asia",
    "Kublai Khan sent fleets against Japan in 1274 and 1281. Both were driven off, and a typhoon wrecked much of the second fleet. Japanese tradition called the storm a divine wind.",
    "The invasions are dated to 1274 and 1281.",
)
add(
    "yuan-dynasty",
    "Kublai Khan proclaims the Yuan",
    "history",
    1271,
    1279,
    39.90,
    116.41,
    "Khanbaliq, Beijing, China",
    "Asia",
    "Kublai Khan proclaimed the Yuan dynasty in 1271 and completed the conquest of the Southern Song in 1279. He ruled China from Khanbaliq, on the site of modern Beijing. Marco Polo's book later described this court to European readers.",
    "The dynasty was proclaimed in 1271, and the Song fell in 1279.",
)
add(
    "majapahit",
    "Majapahit",
    "history",
    1293,
    1527,
    -7.47,
    112.44,
    "Trowulan, Java, Indonesia",
    "Asia",
    "Majapahit arose in east Java in 1293 and became the leading kingdom of the Indonesian archipelago. Its influence is celebrated in the fourteenth-century poem Nagarakretagama. The capital faded in the early sixteenth century as Muslim ports rose.",
    "The kingdom is dated from 1293. Its decline is widely placed in the early 1500s.",
)
add(
    "ibn-battuta",
    "Travels of Ibn Battuta",
    "history",
    1325,
    1354,
    35.76,
    -5.83,
    "Tangier, Morocco",
    "Africa",
    "Ibn Battuta left Tangier in 1325 and travelled for nearly thirty years through Africa, the Middle East, India, Southeast Asia, and China. He dictated an account, the Rihla, after his return. It is a major eyewitness source for the fourteenth-century world.",
    "His travels are dated from 1325 to about 1354.",
)
add(
    "ayutthaya",
    "Foundation of Ayutthaya",
    "history",
    1351,
    1351,
    14.35,
    100.57,
    "Ayutthaya, Thailand",
    "Asia",
    "The kingdom of Ayutthaya was founded in 1351 on an island in the Chao Phraya River. It became a great trading power of mainland Southeast Asia. Burmese armies destroyed the city in 1767.",
    "The traditional foundation date is 1351.",
)
add(
    "zheng-he",
    "Voyages of Zheng He",
    "history",
    1405,
    1433,
    32.06,
    118.78,
    "Nanjing, China",
    "Asia",
    "Between 1405 and 1433 the Ming admiral Zheng He led seven fleets into the Indian Ocean, reaching Arabia and the East African coast. The ships carried diplomats, soldiers, and trade goods. The voyages stopped after his death and were not repeated on that scale.",
    "The seven voyages are dated from 1405 to 1433.",
)
add(
    "hangul",
    "Promulgation of Hangul",
    "history",
    1446,
    1446,
    37.58,
    126.98,
    "Seoul, Korea",
    "Asia",
    "In 1446 King Sejong published Hunminjeongeum, the book that introduced the Korean alphabet now called Hangul. It was designed so that ordinary people could write their language. Classical Chinese remained the script of officials for centuries afterward.",
    "Hunminjeongeum was promulgated in 1446.",
)
add(
    "fall-of-constantinople",
    "Ottoman conquest of Constantinople",
    "history",
    1453,
    1453,
    41.01,
    28.98,
    "Constantinople",
    "Europe",
    "On 29 May 1453 Ottoman forces under Mehmed II took Constantinople, ending the Byzantine Empire. The city, later called Istanbul, became the Ottoman capital. Its fall closed the medieval Roman state in the east.",
    "The city fell on 29 May 1453.",
)
add(
    "babur-panipat",
    "First Battle of Panipat",
    "history",
    1526,
    1526,
    29.39,
    76.97,
    "Panipat, India",
    "Asia",
    "In 1526 Babur defeated the Delhi sultan Ibrahim Lodi at Panipat and founded the Mughal Empire. He used field cannon and a cavalry practised on the steppe. The Mughal state then ruled much of India for three centuries.",
    "The battle was fought on 21 April 1526.",
)
add(
    "imjin-war",
    "Imjin War",
    "history",
    1592,
    1598,
    35.18,
    129.08,
    "Busan, Korea",
    "Asia",
    "Japanese armies under Toyotomi Hideyoshi invaded Korea in 1592 and again after a brief truce. Korean naval victories led by Yi Sun-sin, and Ming Chinese intervention, forced a withdrawal by 1598. The war devastated the Korean peninsula.",
    "The invasions are dated from 1592 to 1598.",
)
add(
    "sekigahara",
    "Battle of Sekigahara",
    "history",
    1600,
    1600,
    35.37,
    136.46,
    "Sekigahara, Japan",
    "Asia",
    "On 21 October 1600 Tokugawa Ieyasu defeated his rivals at Sekigahara. The victory let him establish the Tokugawa shogunate in 1603. That government ruled Japan until 1868.",
    "The battle was fought on 21 October 1600.",
)
add(
    "taj-mahal",
    "Taj Mahal",
    "history",
    1632,
    1653,
    27.17,
    78.04,
    "Agra, India",
    "Asia",
    "The Mughal emperor Shah Jahan built the Taj Mahal as a tomb for Mumtaz Mahal. Work began in 1632 and the main mausoleum was finished in the early 1650s. It stands on the Yamuna at Agra.",
    "Construction began in 1632 and continued into the 1650s.",
)
add(
    "qing-beijing",
    "Qing take Beijing",
    "history",
    1644,
    1644,
    39.90,
    116.41,
    "Beijing, China",
    "Asia",
    "In 1644 a rebel army took Beijing and the last Ming emperor died. Manchu forces then entered the city and established the Qing dynasty. The Qing ruled China until 1912.",
    "Beijing changed hands in 1644.",
)
add(
    "plassey",
    "Battle of Plassey",
    "history",
    1757,
    1757,
    23.80,
    88.25,
    "Plassey, India",
    "Asia",
    "On 23 June 1757 the East India Company under Robert Clive defeated the nawab of Bengal at Plassey. The victory, helped by a secret deal with the nawab's officers, began Company rule in Bengal. It was a turning point in the British conquest of India.",
    "The battle was fought on 23 June 1757.",
)
add(
    "perry-japan",
    "Perry's mission to Japan",
    "history",
    1853,
    1854,
    35.29,
    139.66,
    "Edo Bay, Japan",
    "Asia",
    "In 1853 Commodore Matthew Perry brought United States warships into Edo Bay and demanded that Japan open ports. A treaty followed in 1854. The crisis weakened the Tokugawa government and led toward the Meiji Restoration.",
    "Perry arrived in July 1853. The Treaty of Kanagawa was signed in 1854.",
)
add(
    "indian-rebellion-1857",
    "Indian Rebellion of 1857",
    "history",
    1857,
    1858,
    28.61,
    77.21,
    "Delhi, India",
    "Asia",
    "In 1857 sepoys and a wide range of Indian rulers and towns rose against the East India Company. The fighting was fiercest in northern India and was put down by 1858. Britain then abolished the Company and ruled India directly.",
    "The uprising is dated from May 1857 to 1858.",
)
add(
    "meiji-restoration",
    "Meiji Restoration",
    "history",
    1868,
    1868,
    35.01,
    135.77,
    "Kyoto, Japan",
    "Asia",
    "In 1868 the Tokugawa shogunate fell and power was restored in the name of the emperor Meiji. The new government abolished the domains, built a conscript army, and industrialised. The capital moved to Edo, renamed Tokyo.",
    "The restoration is dated to January 1868.",
)
add(
    "sino-japanese-1895",
    "First Sino-Japanese War",
    "history",
    1894,
    1895,
    37.50,
    126.50,
    "Korea and the Yellow Sea",
    "Asia",
    "War between Japan and Qing China in 1894–1895 was fought over Korea. Japan won, and the Treaty of Shimonoseki gave it Taiwan and influence in Korea. The result shifted the balance of power in East Asia.",
    "The war is dated from July 1894 to April 1895.",
)
add(
    "xinhai",
    "Xinhai Revolution",
    "history",
    1911,
    1912,
    30.59,
    114.31,
    "Wuchang, China",
    "Asia",
    "An uprising at Wuchang in October 1911 spread through the provinces and ended the Qing dynasty. A republic was declared, and the last emperor abdicated in February 1912. Sun Yat-sen was briefly provisional president.",
    "The Wuchang uprising began on 10 October 1911.",
)
add(
    "amritsar",
    "Jallianwala Bagh massacre",
    "history",
    1919,
    1919,
    31.62,
    74.88,
    "Amritsar, India",
    "Asia",
    "On 13 April 1919 British-led troops fired on a crowd gathered at Jallianwala Bagh in Amritsar. Several hundred people were killed. The massacre became a turning point in Indian opposition to colonial rule.",
    "The shooting was on 13 April 1919.",
)
add(
    "may-fourth",
    "May Fourth Movement",
    "history",
    1919,
    1919,
    39.90,
    116.41,
    "Beijing, China",
    "Asia",
    "On 4 May 1919 students in Beijing protested the decision at Versailles to transfer German rights in Shandong to Japan. The protests grew into a wider call for cultural and political change. The movement is a landmark of modern Chinese nationalism.",
    "The Beijing demonstration was on 4 May 1919.",
)
add(
    "nanjing-massacre",
    "Nanjing Massacre",
    "history",
    1937,
    1938,
    32.06,
    118.78,
    "Nanjing, China",
    "Asia",
    "After Japanese troops captured Nanjing in December 1937, they killed a very large number of civilians and prisoners and committed widespread rape. The killing continued for weeks. Estimates of the dead differ, and the massacre itself is documented by diaries, photographs, and the records of the Tokyo trials.",
    "The massacre followed the fall of Nanjing on 13 December 1937.",
)
add(
    "partition-india",
    "Partition of India",
    "history",
    1947,
    1947,
    31.55,
    74.34,
    "Punjab and Bengal",
    "Asia",
    "In August 1947 British India became the independent states of India and Pakistan. Millions of people crossed the new borders, and communal killing took a very large, still disputed, number of lives. The partition remains central to the politics of South Asia.",
    "Independence and partition took effect on 14–15 August 1947.",
)
add(
    "prc-founded",
    "People's Republic of China",
    "history",
    1949,
    1949,
    39.90,
    116.39,
    "Beijing, China",
    "Asia",
    "On 1 October 1949 Mao Zedong proclaimed the People's Republic of China in Beijing. The Nationalist government retreated to Taiwan. The civil war's main campaigns on the mainland were over.",
    "The proclamation was on 1 October 1949.",
)
add(
    "korean-war",
    "Korean War",
    "history",
    1950,
    1953,
    37.57,
    126.98,
    "Korean peninsula",
    "Asia",
    "War began on 25 June 1950 when North Korean forces invaded the South. United Nations forces, largely American, and later Chinese armies, fought until an armistice in 1953. No peace treaty was signed, and the peninsula stayed divided.",
    "The war is dated from 25 June 1950 to the armistice of 27 July 1953.",
)
add(
    "dien-bien-phu",
    "Battle of Dien Bien Phu",
    "history",
    1954,
    1954,
    21.39,
    103.01,
    "Dien Bien Phu, Vietnam",
    "Asia",
    "Viet Minh forces defeated the French garrison at Dien Bien Phu in May 1954. The victory ended French colonial rule in Indochina. The Geneva conference that summer divided Vietnam temporarily at the 17th parallel.",
    "The garrison surrendered on 7 May 1954.",
)
add(
    "great-leap",
    "Great Leap Forward",
    "history",
    1958,
    1962,
    34.26,
    108.94,
    "China",
    "Asia",
    "The Great Leap Forward of 1958 tried to industrialise China at great speed through communes and backyard steel. It was followed by a famine. Death tolls are estimated in the tens of millions, and the exact figure is disputed.",
    "The campaign and the famine are dated to 1958–1962.",
)
add(
    "cultural-revolution",
    "Cultural Revolution",
    "history",
    1966,
    1976,
    39.90,
    116.41,
    "Beijing, China",
    "Asia",
    "In 1966 Mao Zedong launched the Cultural Revolution, and student Red Guards attacked officials, teachers, and historic sites. The turmoil lasted until Mao's death in 1976. It disrupted schools, families, and the Communist Party itself.",
    "The movement is dated from 1966 to 1976.",
)
add(
    "iranian-revolution",
    "Iranian Revolution",
    "history",
    1979,
    1979,
    35.69,
    51.39,
    "Tehran, Iran",
    "Asia",
    "Mass protests in 1978–1979 overthrew the shah, Mohammad Reza Pahlavi. Ayatollah Ruhollah Khomeini returned from exile and an Islamic republic was declared. The revolution reshaped the politics of the Middle East.",
    "The shah left Iran on 16 January 1979, and the republic was declared on 1 April 1979.",
)
add(
    "tiananmen-1989",
    "Tiananmen Square protests",
    "history",
    1989,
    1989,
    39.91,
    116.40,
    "Beijing, China",
    "Asia",
    "In the spring of 1989 students and workers occupied Tiananmen Square calling for reform. On 3–4 June the army cleared Beijing by force, killing an unknown number of people. Public discussion of the crackdown is still censored in China.",
    "The military assault was on the night of 3–4 June 1989.",
)
add(
    "hong-kong-handover",
    "Handover of Hong Kong",
    "history",
    1997,
    1997,
    22.28,
    114.16,
    "Hong Kong",
    "Asia",
    "On 1 July 1997 Britain returned Hong Kong to China under an agreement that promised a separate system for fifty years. The handover ended more than 150 years of British rule. Later political conflict has tested that promise.",
    "The handover was at midnight on 1 July 1997.",
)
add(
    "timor-leste",
    "Independence of Timor-Leste",
    "history",
    2002,
    2002,
    -8.56,
    125.58,
    "Dili, Timor-Leste",
    "Asia",
    "East Timor voted for independence from Indonesia in a 1999 referendum, after a long occupation. It became the state of Timor-Leste on 20 May 2002. Indonesian-backed militias had killed many civilians after the vote.",
    "Independence was restored on 20 May 2002.",
)
add(
    "indian-ocean-tsunami",
    "Indian Ocean tsunami",
    "history",
    2004,
    2004,
    3.32,
    95.85,
    "Off the coast of Aceh, Indonesia",
    "Asia",
    "On 26 December 2004 an earthquake off Sumatra caused a tsunami that killed more than 200,000 people around the Indian Ocean. Aceh was the worst hit. The disaster led to a large international relief effort.",
    "The earthquake was on 26 December 2004.",
)
add(
    "arab-spring-egypt",
    "Egyptian uprising of 2011",
    "history",
    2011,
    2011,
    30.04,
    31.24,
    "Cairo, Egypt",
    "Africa",
    "Protests in Cairo's Tahrir Square in January and February 2011 forced President Hosni Mubarak to resign. The uprising followed the revolution in Tunisia. The years after brought elections, a coup in 2013, and a return to strong military rule.",
    "Mubarak resigned on 11 February 2011.",
)
add(
    "rohingya-2017",
    "Expulsion of the Rohingya",
    "history",
    2017,
    2017,
    20.85,
    92.30,
    "Rakhine State, Myanmar",
    "Asia",
    "In August 2017 the Myanmar army drove hundreds of thousands of Rohingya Muslims from Rakhine State into Bangladesh. Villages were burned and large numbers of civilians were killed. United Nations investigators later described the campaign as genocide.",
    "The main campaign began in late August 2017.",
)
add(
    "covid-identified",
    "COVID-19 pandemic",
    "history",
    2019,
    2023,
    30.59,
    114.30,
    "Wuhan, China",
    "Asia",
    "A new coronavirus was identified in Wuhan in late 2019 and spread worldwide. The World Health Organization described the outbreak as a pandemic in March 2020. It killed millions of people and shut down travel and daily life on every continent.",
    "The virus was first identified in Wuhan in December 2019. The pandemic declaration was on 11 March 2020.",
)
add(
    "enuma-elish",
    "Enuma Elish",
    "myth",
    -1200,
    -1100,
    32.54,
    44.42,
    "Babylon, Iraq",
    "Asia",
    "The Enuma Elish tells how Marduk defeated the sea Tiamat and built the world from her body. It is the great creation epic of Babylon. The classic form of the poem is known from tablets of the late second millennium BCE, and the story is older.",
    "Earliest written source. The standard Babylonian text is widely placed in the late second millennium BCE.",
)
add(
    "gilgamesh",
    "Epic of Gilgamesh",
    "myth",
    -2100,
    -1800,
    31.32,
    45.64,
    "Uruk, Iraq",
    "Asia",
    "Gilgamesh, a king of Uruk, is the hero of poems about friendship, the wilderness, and the search for eternal life. Sumerian tales about him were written down by about 2100 BCE. The famous standard Akkadian version is later.",
    "Earliest written source. Sumerian Gilgamesh poems were copied by about 2100 BCE. A traditional reign in the distant past is not a usable calendar date.",
)
add(
    "inanna-descent",
    "Inanna's descent",
    "myth",
    -1900,
    -1700,
    31.32,
    45.64,
    "Uruk, Iraq",
    "Asia",
    "In this Sumerian myth the goddess Inanna descends to the underworld, is killed, and is brought back. Old Babylonian tablets preserve the poem. It belongs to Uruk, her city.",
    "Earliest written source. The poem is known from Old Babylonian copies of about the nineteenth to seventeenth centuries BCE.",
)
add(
    "ramayana",
    "Ramayana",
    "myth",
    -400,
    200,
    26.80,
    82.20,
    "Ayodhya, India",
    "Asia",
    "The Ramayana tells of Rama's exile and the rescue of Sita from Lanka. Traditional sacred chronology places the story in a remote mythical age, not a historical century. The surviving epic was composed in the first millennium BCE and the early centuries CE.",
    "Earliest written source. Composition is widely placed between about 400 BCE and 200 CE. There is no agreed historical year for the tale.",
)
add(
    "mahabharata",
    "Mahabharata",
    "myth",
    -400,
    400,
    29.99,
    76.83,
    "Kurukshetra, India",
    "Asia",
    "The Mahabharata tells of a war between cousin clans on the field of Kurukshetra, and it includes the Bhagavad Gita. Its traditional setting is a heroic age without an agreed calendar date. The written epic grew between about 400 BCE and 400 CE.",
    "Earliest written source. The written epic grew over the centuries from about 400 BCE to 400 CE.",
)
add(
    "dangun",
    "Dangun founds Gojoseon",
    "myth",
    -2333,
    -2333,
    37.97,
    126.55,
    "Korea",
    "Asia",
    "Korean tradition says that Dangun, born of a heavenly prince and a bear-woman, founded the first Korean kingdom in 2333 BCE. The story is a national origin myth, not a historical record. It was written down much later, notably in the thirteenth-century Samguk Yusa.",
    "Traditional date. The year 2333 BCE is the traditional founding date, recorded many centuries later.",
)
add(
    "jimmu",
    "Emperor Jimmu",
    "myth",
    -660,
    -660,
    34.50,
    135.80,
    "Yamato, Japan",
    "Asia",
    "Japanese official tradition dated the accession of the first emperor, Jimmu, to 660 BCE. The tale, in which he descends from the sun goddess, is a foundation myth. It was set down in the Kojiki of 712 and the Nihon Shoki of 720.",
    "Traditional date. 660 BCE is the traditional accession year, written down in the eighth century.",
)
add(
    "izanagi-kojiki",
    "Izanagi and Izanami",
    "myth",
    712,
    712,
    35.01,
    135.77,
    "Japan",
    "Asia",
    "The Kojiki tells how the creator couple Izanagi and Izanami stirred the sea and brought forth the Japanese islands. It is the oldest surviving Japanese book. The myths it records are older than the writing.",
    "Earliest written source. The Kojiki was completed in 712. The tradition is older.",
)
add(
    "pangu",
    "Pangu separates heaven and earth",
    "myth",
    220,
    280,
    34.75,
    113.65,
    "China",
    "Asia",
    "Pangu is said to have grown inside a cosmic egg and then pushed heaven and earth apart. The written story is late compared with other Chinese myths. It is first attributed to Xu Zheng in the Three Kingdoms period.",
    "Earliest written source. The tale is credited to Xu Zheng in the third century CE.",
)
add(
    "change-myth",
    "Chang'e flies to the moon",
    "myth",
    -139,
    -139,
    32.00,
    117.00,
    "China",
    "Asia",
    "Chang'e is the goddess who flies to the moon after taking an elixir of immortality. The story is older than any single book, and a famous early telling is in the Huainanzi. That book was presented to the Han court in 139 BCE.",
    "Earliest written source. The Huainanzi, presented in 139 BCE, contains an early written telling.",
)
add(
    "journey-to-the-west",
    "Journey to the West",
    "myth",
    1592,
    1592,
    34.75,
    113.65,
    "China",
    "Asia",
    "Journey to the West turns the historical pilgrimage of the monk Xuanzang into a fantasy of demons, with the monkey king Sun Wukong as its hero. The novel was published in the sixteenth century. Xuanzang's real journey, in the seventh century, is a separate historical event.",
    "Earliest written source. The novel was published in the sixteenth century, traditionally in 1592.",
)
add(
    "xuanzang",
    "Xuanzang's pilgrimage",
    "history",
    629,
    645,
    34.26,
    108.94,
    "Chang'an to India",
    "Asia",
    "The monk Xuanzang left China in 629, travelled to India, and returned in 645 with Buddhist texts. His own Record of the Western Regions describes the kingdoms he saw. The novel Journey to the West later turned the journey into myth.",
    "He departed in 629 and returned in 645.",
)
add(
    "trojan-war",
    "Trojan War",
    "myth",
    -1184,
    -1184,
    39.96,
    26.24,
    "Troy, Turkey",
    "Asia",
    "Greek tradition tells of a Greek war against Troy to recover Helen, ending in the city's fall. Eratosthenes dated that fall to 1184 BCE. The Iliad is poetry, and a historical war on that scale is not established, though Troy was a real Late Bronze Age city.",
    "Traditional date. Eratosthenes placed the fall of Troy in 1184 BCE.",
)
add(
    "troy-bronze-age",
    "Bronze Age Troy",
    "history",
    -1700,
    -1180,
    39.96,
    26.24,
    "Hisarlik, Turkey",
    "Asia",
    "The mound at Hisarlik was a fortified city through the Bronze Age, identified with the Troy of later Greek story. Several layers were destroyed, including one around 1180 BCE. Archaeology does not confirm the Homeric war, which is marked separately as myth.",
    "Approximate. Late Bronze Age Troy was occupied until destructions around 1180 BCE.",
)
add(
    "petra",
    "Petra",
    "history",
    -100,
    100,
    30.33,
    35.44,
    "Petra, Jordan",
    "Asia",
    "Petra, carved into sandstone cliffs, was the capital of the Nabataean kingdom. Its monumental tombs and the treasury facade are widely dated around the first centuries BCE and CE. The city controlled caravan trade between Arabia and the Mediterranean.",
    "Approximate. The major monuments are widely dated around the turn of the era.",
)
