from lib import add

add(
    "bacho-kiro",
    "Homo sapiens at Bacho Kiro",
    "history",
    -45000,
    -43000,
    42.95,
    25.43,
    "Bacho Kiro Cave, Bulgaria",
    "Europe",
    "Teeth and bone fragments from Bacho Kiro are among the oldest widely accepted Homo sapiens remains in Europe. They are dated to about 45,000 years ago. The people there used ornaments and lived near the last Neanderthals.",
    "Approximate. The remains are dated to about 45,000 years ago.",
)
add(
    "neanderthals-end",
    "Last Neanderthals",
    "history",
    -41000,
    -39000,
    46.30,
    16.07,
    "Vindija Cave, Croatia",
    "Europe",
    "Neanderthals disappeared from Europe around 40,000 years ago. Radiocarbon work led by Tom Higham places the last widely dated sites in that window. They left DNA in living people whose ancestors lived outside Africa.",
    "Approximate. The last European Neanderthals are widely dated to about 40,000 years ago.",
)
add(
    "lion-man",
    "Lion-man of Hohlenstein",
    "history",
    -40000,
    -40000,
    48.55,
    10.17,
    "Hohlenstein-Stadel, Germany",
    "Europe",
    "A mammoth-ivory figure with a human body and a lion's head was found in a cave on the Swabian Jura. It is dated to about 40,000 years ago. It is one of the oldest known statues.",
    "Approximate. The figure is dated to about 40,000 years ago.",
)
add(
    "chauvet",
    "Chauvet Cave",
    "history",
    -36000,
    -33000,
    44.39,
    4.42,
    "Chauvet Cave, France",
    "Europe",
    "Chauvet Cave holds paintings of lions, rhinos, and horses dated to about 36,000 to 33,000 years ago. The art is older than Lascaux by many millennia. The cave was sealed for most of later prehistory, which preserved the paintings.",
    "Approximate. The paintings are widely dated to about 36,000–33,000 years ago.",
)
add(
    "willendorf",
    "Venus of Willendorf",
    "history",
    -27500,
    -27500,
    48.32,
    15.40,
    "Willendorf, Austria",
    "Europe",
    "A small limestone figure of a woman, found at Willendorf, is dated to about 29,500 years ago, around 27,500 BCE. It was carved and once painted during the last Ice Age. Its purpose is unknown.",
    "Approximate. The figurine is dated to about 29,500 years ago.",
)
add(
    "last-glacial-maximum",
    "Last Glacial Maximum",
    "history",
    -24000,
    -17000,
    62.00,
    15.00,
    "Fennoscandian ice sheet",
    "Europe",
    "About 26,000 to 19,000 years ago, ice sheets reached their greatest recent extent across northern Europe and North America. Sea level was far lower, and people lived south of the ice. This pin marks the Fennoscandian sheet; the climate event was global.",
    "Approximate. The maximum is widely dated to about 26,000–19,000 years ago. The years stored here are the BCE equivalents.",
)
add(
    "lascaux",
    "Lascaux",
    "history",
    -17000,
    -17000,
    45.05,
    1.17,
    "Lascaux, France",
    "Europe",
    "The paintings of horses, bulls, and deer at Lascaux are widely dated to about 17,000 BCE. The cave was found in 1940 and later closed to protect the art. A replica now receives visitors.",
    "Approximate. The paintings are widely dated to about 17,000 BCE.",
)
add(
    "altamira",
    "Altamira",
    "history",
    -14000,
    -13500,
    43.38,
    -4.12,
    "Altamira, Spain",
    "Europe",
    "The bison painted on the ceiling of Altamira are widely dated to the later Magdalenian, around 15,000 to 13,500 years ago. When the cave was found in the nineteenth century, many scholars refused to believe Ice Age people had made them. That doubt did not last.",
    "Approximate. The famous ceiling is widely dated to about 15,000–13,500 years ago.",
)
add(
    "stonehenge",
    "Stonehenge",
    "history",
    -3000,
    -2200,
    51.18,
    -1.83,
    "Stonehenge, England",
    "Europe",
    "An earthwork enclosure at Stonehenge began around 3000 BCE, and the great sarsen circle was raised around 2500 BCE. The stones were brought from Wales and from nearer quarries. The monument stayed in use for ceremonies and burials.",
    "Approximate. The enclosure begins around 3000 BCE and the sarsen circle around 2500 BCE.",
)
add(
    "knossos",
    "Palace of Knossos",
    "history",
    -1900,
    -1375,
    35.30,
    25.16,
    "Knossos, Crete",
    "Europe",
    "Knossos was the largest palace of Minoan Crete, with courtyards, storerooms, and colourful frescoes. The first palaces rose around 1900 BCE. Later Greek myth placed the Minotaur here, which is a separate tradition from the archaeology.",
    "Approximate. The first palace phase is widely dated to about 1900 BCE.",
)
add(
    "roman-republic",
    "Roman Republic",
    "history",
    -509,
    -27,
    41.89,
    12.49,
    "Rome, Italy",
    "Europe",
    "Roman tradition dated the expulsion of the kings and the start of the Republic to 509 BCE. The state then expanded from a city to a Mediterranean power. It ended as a republic when Augustus established the principate in 27 BCE.",
    "The traditional start is 509 BCE. Augustus's settlement is dated to 27 BCE.",
)
add(
    "marathon",
    "Battle of Marathon",
    "history",
    -490,
    -490,
    38.12,
    23.98,
    "Marathon, Greece",
    "Europe",
    "In 490 BCE an Athenian and Plataean army defeated a Persian landing force at Marathon. The battle stopped the first Persian invasion of mainland Greece. A second, larger invasion followed ten years later.",
    "The battle is dated to 490 BCE.",
)
add(
    "salamis",
    "Battle of Salamis",
    "history",
    -480,
    -480,
    37.95,
    23.54,
    "Salamis, Greece",
    "Europe",
    "In 480 BCE Greek fleets defeated the Persian navy of Xerxes in the straits of Salamis. The victory followed the Persian sack of Athens and the stand at Thermopylae. It turned the second Persian invasion.",
    "The battle is dated to 480 BCE.",
)
add(
    "socrates",
    "Trial of Socrates",
    "history",
    -399,
    -399,
    37.97,
    23.72,
    "Athens, Greece",
    "Europe",
    "An Athenian jury condemned the philosopher Socrates to death in 399 BCE. Plato and Xenophon, his students, wrote accounts of the trial and of his last day. He was charged with impiety and with corrupting the young.",
    "The trial is dated to 399 BCE.",
)
add(
    "caesar-death",
    "Assassination of Caesar",
    "history",
    -44,
    -44,
    41.89,
    12.49,
    "Rome, Italy",
    "Europe",
    "On 15 March 44 BCE a group of senators stabbed Julius Caesar in the Theatre of Pompey. They claimed to be saving the Republic. Civil wars followed, and the Republic did not survive them.",
    "Caesar was killed on 15 March 44 BCE.",
)
add(
    "pompeii",
    "Eruption of Vesuvius",
    "history",
    79,
    79,
    40.75,
    14.49,
    "Pompeii, Italy",
    "Europe",
    "In 79 CE Vesuvius buried Pompeii and Herculaneum under ash and pumice. Pliny the Younger described the eruption in letters written afterward. The buried cities preserve streets, houses, and bodies from a single day.",
    "The eruption is dated to 79 CE, traditionally 24 August, though some evidence points to the autumn.",
)
add(
    "nicaea",
    "Council of Nicaea",
    "history",
    325,
    325,
    40.43,
    29.72,
    "Nicaea, Turkey",
    "Asia",
    "In 325 the emperor Constantine called bishops to Nicaea to settle disputes about the nature of Christ. The council produced a creed that most later churches accepted in revised form. It was an imperial intervention in Christian doctrine.",
    "The council met in 325.",
)
add(
    "fall-of-rome",
    "End of the western Roman Empire",
    "history",
    476,
    476,
    45.44,
    12.32,
    "Ravenna, Italy",
    "Europe",
    "In 476 the soldier Odoacer deposed Romulus Augustulus, the last western emperor, at Ravenna. The eastern empire in Constantinople continued. Later writers treated 476 as the end of the western Roman Empire, though the change was less sudden than that date suggests.",
    "Romulus Augustulus was deposed in 476.",
)
add(
    "justinian",
    "Reign of Justinian",
    "history",
    527,
    565,
    41.01,
    28.98,
    "Constantinople",
    "Europe",
    "Justinian I ruled the eastern Roman Empire from 527 to 565. His lawyers produced the Corpus Juris Civilis, and Hagia Sophia was rebuilt after riots in 532. His armies retook parts of Italy and North Africa for a time.",
    "Justinian ruled from 527 to 565.",
)
add(
    "lindisfarne",
    "Raid on Lindisfarne",
    "history",
    793,
    793,
    55.67,
    -1.80,
    "Lindisfarne, England",
    "Europe",
    "In 793 a Viking fleet raided the monastery of Lindisfarne off the Northumbrian coast. The Anglo-Saxon Chronicle treats the attack as a famous early blow of the Viking age in Britain. Raids and settlement then spread around the North Sea and the Atlantic.",
    "The raid is dated to 8 June 793.",
)
add(
    "viking-voyages",
    "Viking voyages west",
    "history",
    870,
    1000,
    60.39,
    5.32,
    "Western Norway",
    "Europe",
    "Norse sailors settled Iceland from about 870, Greenland from about 980, and reached Newfoundland around 1000. The site at L'Anse aux Meadows is the archaeological trace of that American landfall. The line is a schematic of the western route.",
    "Approximate. Iceland was settled from about 870, and the Newfoundland site dates to around 1000.",
    path=[
        (60.4, 5.3),
        (64.1, -21.9),
        (61.2, -48.0),
        (51.6, -55.53),
    ],
)
add(
    "charlemagne",
    "Coronation of Charlemagne",
    "history",
    800,
    800,
    41.90,
    12.45,
    "Rome, Italy",
    "Europe",
    "On Christmas Day 800 Pope Leo III crowned Charlemagne emperor in St Peter's. Charlemagne already ruled the Franks and the Lombards from Aachen. The coronation revived an imperial title in the west.",
    "The coronation was on 25 December 800.",
)
add(
    "lanse-aux-meadows",
    "L'Anse aux Meadows",
    "history",
    1000,
    1000,
    51.60,
    -55.53,
    "L'Anse aux Meadows, Newfoundland",
    "North America",
    "Norse buildings at L'Anse aux Meadows are dated to around the year 1000. They are the only widely accepted Viking site in North America. The settlement was short-lived.",
    "Approximate. The occupation is widely dated to around 1000.",
)
add(
    "hastings",
    "Norman conquest",
    "history",
    1066,
    1066,
    50.91,
    0.49,
    "Hastings, England",
    "Europe",
    "On 14 October 1066 William of Normandy defeated King Harold at Hastings. William was crowned in Westminster Abbey that Christmas. The conquest replaced the English elite and tied England to northern France.",
    "The battle was fought on 14 October 1066.",
)
add(
    "magna-carta",
    "Magna Carta",
    "history",
    1215,
    1215,
    51.44,
    -0.56,
    "Runnymede, England",
    "Europe",
    "In June 1215 rebel barons forced King John to seal Magna Carta at Runnymede. The charter limited some royal abuses and was reissued by later kings. A few of its clauses became famous in later arguments about law and liberty.",
    "The charter was sealed on 15 June 1215.",
)
add(
    "black-death",
    "Black Death",
    "history",
    1347,
    1353,
    38.19,
    15.55,
    "Messina, Sicily",
    "Europe",
    "Plague reached Messina in 1347 and spread across Europe, North Africa, and the Middle East within a few years. It killed a very large share of the population, widely estimated at around a third in Europe. The disease was caused by the bacterium Yersinia pestis.",
    "The European outbreak is dated from 1347 to about 1353.",
)
add(
    "gutenberg",
    "Gutenberg Bible",
    "history",
    1455,
    1455,
    49.99,
    8.27,
    "Mainz, Germany",
    "Europe",
    "Johannes Gutenberg printed a Latin Bible at Mainz in the 1450s, using movable metal type. It is the first major European book printed this way. Printing then spread quickly across the continent.",
    "The Bible was completed around 1455.",
)
add(
    "luther",
    "Luther's theses",
    "history",
    1517,
    1517,
    51.87,
    12.64,
    "Wittenberg, Germany",
    "Europe",
    "In 1517 Martin Luther circulated ninety-five theses criticising indulgences. The protest, spread by print, began the Protestant Reformation. Luther was later outlawed by the emperor and protected by the elector of Saxony.",
    "The theses are dated to 31 October 1517.",
)
add(
    "copernicus",
    "De revolutionibus",
    "history",
    1543,
    1543,
    53.78,
    20.49,
    "Frombork, Poland",
    "Europe",
    "Nicolaus Copernicus's book On the Revolutions of the Heavenly Spheres was published in 1543, the year he died. It set the Sun, not the Earth, at the centre of the planetary system. The idea spread slowly and was later defended by Galileo and Kepler.",
    "The book was published in 1543.",
)
add(
    "spanish-armada",
    "Spanish Armada",
    "history",
    1588,
    1588,
    50.10,
    -5.50,
    "English Channel",
    "Europe",
    "In 1588 Philip II sent a fleet to escort an invasion of England. English ships and storms broke the Armada, and many of the surviving ships were wrecked on the voyage home around Scotland and Ireland. The defeat did not end the war.",
    "The campaign was in the summer of 1588.",
)
add(
    "galileo-moons",
    "Galileo's telescopic discoveries",
    "history",
    1610,
    1610,
    43.77,
    11.26,
    "Padua, Italy",
    "Europe",
    "In 1610 Galileo Galilei published Sidereus Nuncius, describing mountains on the Moon and four moons orbiting Jupiter. He had seen them with a telescope he improved. The moons showed that not everything in the sky circled the Earth.",
    "Sidereus Nuncius was published in March 1610.",
)
add(
    "newton-principia",
    "Newton's Principia",
    "history",
    1687,
    1687,
    52.21,
    0.12,
    "Cambridge, England",
    "Europe",
    "Isaac Newton's Principia, published in 1687, set out the laws of motion and a universal law of gravitation. It explained the orbits of planets and the fall of objects with one theory. The book became the foundation of later physics.",
    "The Principia was published in 1687.",
)
add(
    "lisbon-earthquake",
    "Lisbon earthquake",
    "history",
    1755,
    1755,
    38.72,
    -9.14,
    "Lisbon, Portugal",
    "Europe",
    "On 1 November 1755 an earthquake and tsunami destroyed much of Lisbon and shook the western Mediterranean. Tens of thousands of people died. The disaster fed Enlightenment arguments about God, nature, and the duty of states to rebuild.",
    "The earthquake was on 1 November 1755.",
)
add(
    "watt-engine",
    "Watt's steam engine",
    "history",
    1769,
    1776,
    55.86,
    -4.25,
    "Glasgow and Birmingham",
    "Europe",
    "James Watt patented a separate condenser for the steam engine in 1769, greatly improving earlier engines. With Matthew Boulton he began selling engines in the 1770s. The improved engine powered mines and, later, factories.",
    "The patent is dated 1769. Commercial engines followed in the 1770s.",
)
add(
    "french-revolution",
    "French Revolution",
    "history",
    1789,
    1799,
    48.86,
    2.35,
    "Paris, France",
    "Europe",
    "In 1789 the French Estates-General became a national assembly and a crowd stormed the Bastille. The revolution abolished feudal privileges, executed the king in 1793, and slid into the Terror and war. Napoleon took power in 1799.",
    "The revolution is dated from 1789. The coup of 18 Brumaire was in November 1799.",
)
add(
    "revolutions-1848",
    "Revolutions of 1848",
    "history",
    1848,
    1849,
    48.21,
    16.37,
    "Vienna and Paris",
    "Europe",
    "In 1848 revolutions broke out from Paris to Vienna, Berlin, and Milan, demanding constitutions and national rights. Most of the uprisings were defeated within a year. They still ended serfdom in the Austrian Empire and spread liberal and nationalist politics.",
    "The main wave is dated to 1848–1849.",
)
add(
    "italian-unification",
    "Unification of Italy",
    "history",
    1861,
    1870,
    41.90,
    12.48,
    "Rome and Turin",
    "Europe",
    "The kingdom of Italy was proclaimed in 1861 after the campaigns of Garibaldi and the house of Savoy. Venice joined in 1866 and Rome in 1870, when Italian troops entered the city. The Papal States then shrank to the Vatican.",
    "The kingdom was proclaimed on 17 March 1861. Rome was taken in 1870.",
)
add(
    "german-unification",
    "German Empire",
    "history",
    1871,
    1871,
    48.80,
    2.12,
    "Versailles, France",
    "Europe",
    "On 18 January 1871 the German Empire was proclaimed in the Hall of Mirrors at Versailles, after Prussia defeated France. Otto von Bismarck had united the German states under the Prussian king. The empire lasted until 1918.",
    "The empire was proclaimed on 18 January 1871.",
)
add(
    "berlin-conference",
    "Berlin Conference",
    "history",
    1884,
    1885,
    52.51,
    13.38,
    "Berlin, Germany",
    "Europe",
    "From November 1884 to February 1885 European powers met in Berlin to set rules for claiming colonies in Africa. No African state was a party to the decisions. The conference sped the partition of the continent.",
    "The conference met from 15 November 1884 to 26 February 1885.",
)
add(
    "wwi",
    "First World War",
    "history",
    1914,
    1918,
    43.86,
    18.42,
    "Sarajevo",
    "Europe",
    "The assassination of Archduke Franz Ferdinand in Sarajevo on 28 June 1914 began the July crisis and a continental war. The fighting killed about ten million soldiers and ended the Russian, German, Austro-Hungarian, and Ottoman empires. An armistice was signed on 11 November 1918.",
    "The war is dated from 28 July 1914 to 11 November 1918.",
)
add(
    "russian-revolution",
    "Russian Revolution",
    "history",
    1917,
    1917,
    59.94,
    30.31,
    "Petrograd, Russia",
    "Europe",
    "In February 1917 protests in Petrograd overthrew the tsar. In October the Bolsheviks, led by Lenin, seized power from the provisional government. A civil war followed, and the Soviet state emerged from it.",
    "The two revolutions are dated to March and November 1917 in the modern calendar.",
)
add(
    "wwii-europe",
    "Second World War in Europe",
    "history",
    1939,
    1945,
    52.23,
    21.01,
    "Poland",
    "Europe",
    "Germany invaded Poland on 1 September 1939, and Britain and France declared war two days later. The war in Europe killed tens of millions of people and ended with Germany's surrender in May 1945. It was fought alongside the war in Asia and the Pacific.",
    "The European war is dated from 1 September 1939 to 8 May 1945.",
)
add(
    "holocaust",
    "The Holocaust",
    "history",
    1941,
    1945,
    50.04,
    19.18,
    "Auschwitz, Poland",
    "Europe",
    "Nazi Germany and its collaborators murdered about six million Jews, and millions of Roma, disabled people, prisoners of war, and other civilians. Auschwitz-Birkenau was the largest of the killing centres. The genocide is documented by German records, survivor testimony, and the sites themselves.",
    "The systematic murder is dated chiefly to 1941–1945.",
)
add(
    "chernobyl",
    "Chernobyl disaster",
    "history",
    1986,
    1986,
    51.39,
    30.10,
    "Chernobyl, Ukraine",
    "Europe",
    "On 26 April 1986 a reactor at the Chernobyl nuclear plant exploded during a test. A radioactive cloud spread across Europe, and a large zone around the plant was abandoned. The disaster shook confidence in the Soviet system.",
    "The explosion was on 26 April 1986.",
)
add(
    "fall-of-the-wall",
    "Fall of the Berlin Wall",
    "history",
    1989,
    1989,
    52.52,
    13.40,
    "Berlin, Germany",
    "Europe",
    "On 9 November 1989 East German authorities opened the Berlin Wall, and crowds crossed freely. The wall had divided the city since 1961. German reunification followed in 1990, and the Soviet Union dissolved in 1991.",
    "The border opened on the night of 9 November 1989.",
)
add(
    "world-wide-web",
    "World Wide Web",
    "history",
    1991,
    1991,
    46.23,
    6.05,
    "CERN, Switzerland",
    "Europe",
    "Tim Berners-Lee, working at CERN, proposed the World Wide Web in 1989 and released it to the public in 1991. The web used hypertext links on top of the existing internet. It became the main public face of the network.",
    "The web was released outside CERN in 1991. The proposal is dated 1989.",
)
add(
    "good-friday",
    "Good Friday Agreement",
    "history",
    1998,
    1998,
    54.60,
    -5.93,
    "Belfast",
    "Europe",
    "On 10 April 1998 the British and Irish governments and the Northern Irish parties signed the Good Friday Agreement. It set up power-sharing and a path to end the Troubles. Voters in Ireland, north and south, approved it in referendums.",
    "The agreement was signed on 10 April 1998.",
)
add(
    "rome-founding",
    "Founding of Rome",
    "myth",
    -753,
    -753,
    41.89,
    12.49,
    "Rome, Italy",
    "Europe",
    "Roman tradition said the city was founded by Romulus on 21 April 753 BCE. The tale of the twins, the she-wolf, and the killing of Remus is myth. Archaeology shows villages on the Roman hills centuries earlier, without confirming that year.",
    "Traditional date. Later Roman writers placed the founding in 753 BCE.",
)
add(
    "hesiod-prometheus",
    "Prometheus and Pandora",
    "myth",
    -700,
    -700,
    38.35,
    23.10,
    "Boeotia, Greece",
    "Europe",
    "Hesiod tells how Prometheus stole fire for humans and how Zeus sent Pandora, whose jar released evils into the world. The poems, the Theogony and Works and Days, are the earliest full written versions. They were composed around 700 BCE.",
    "Earliest written source. Hesiod's poems are widely dated to around 700 BCE.",
)
add(
    "theseus",
    "Theseus and the Minotaur",
    "myth",
    -450,
    -400,
    37.97,
    23.72,
    "Athens, Greece",
    "Europe",
    "Athenian tradition made Theseus the hero who slew the Minotaur in the labyrinth of Crete and united Attica. There is no agreed historical year for his life. The story is fully visible in classical Athenian art and writing of the fifth century BCE.",
    "Earliest written source. The tale is well established in fifth-century BCE Athenian sources. No traditional calendar year is secure.",
)
add(
    "beowulf",
    "Beowulf",
    "myth",
    1000,
    1000,
    51.75,
    -1.26,
    "England",
    "Europe",
    "Beowulf tells of a Geatish hero who kills the monster Grendel and, in old age, a dragon. The only surviving manuscript was written in England around the year 1000. The poem's story is set in Scandinavia and is older than that copy.",
    "Earliest written source. The surviving manuscript is dated to around 1000.",
)
add(
    "king-arthur",
    "King Arthur",
    "myth",
    830,
    830,
    51.38,
    -2.36,
    "Britain",
    "Europe",
    "Arthur appears as a British war leader in the ninth-century Historia Brittonum, and later medieval romances made him a king of a round table. There is no agreed historical date for his life, and a real Arthur is uncertain. The legend belongs to Britain and Brittany.",
    "Earliest written source. The Historia Brittonum, around 830, is the earliest substantial written mention.",
)
add(
    "ragnarok",
    "Ragnarök",
    "myth",
    1270,
    1270,
    64.15,
    -21.94,
    "Iceland",
    "Europe",
    "Norse myth tells of Ragnarök, the last battle in which gods and giants kill one another and the world is remade. The fullest written versions are in the Icelandic Eddas. The Poetic Edda's main manuscript, the Codex Regius, is from about 1270.",
    "Earliest written source. The Codex Regius is dated to about 1270. The oral tradition is older.",
)
add(
    "tain",
    "The Táin",
    "myth",
    1100,
    1200,
    53.99,
    -6.40,
    "Ireland",
    "Europe",
    "The Táin Bó Cúailnge tells how the young hero Cú Chulainn defended Ulster against the armies of Connacht. It is the centre of the Irish Ulster Cycle. The oldest substantial manuscripts are from the twelfth century, and the stories are older.",
    "Earliest written source. The main manuscripts are medieval, from about the twelfth century.",
)
add(
    "kalevala",
    "Kalevala",
    "myth",
    1835,
    1849,
    62.90,
    30.00,
    "Karelia and Finland",
    "Europe",
    "Elias Lönnrot compiled the Kalevala from Finnish and Karelian oral poems and published it in 1835, with a longer edition in 1849. It tells of the singer Väinämöinen and the smith Ilmarinen. The oral poems are older than the book.",
    "Earliest written source. Lönnrot's compilation was published in 1835 and enlarged in 1849.",
)
add(
    "genesis-flood",
    "The biblical flood",
    "myth",
    -600,
    -500,
    31.78,
    35.23,
    "Ancient Israel",
    "Asia",
    "Genesis tells of Noah, who survives a flood that covers the world. Related flood stories are older in Mesopotamia, and those are separate traditions. The biblical text as we have it was written down in the first millennium BCE.",
    "Earliest written source. The written Genesis flood is widely placed in the first millennium BCE. Mesopotamian flood poems are older and are not this text.",
)
