from lib import add

add(
    "madjedbebe",
    "Settlement of Sahul",
    "history",
    -65000,
    -50000,
    -12.48,
    132.88,
    "Madjedbebe, Australia",
    "Oceania",
    "People had reached Sahul, the Ice Age continent of Australia and New Guinea, by about 50,000 years ago. Excavations at Madjedbebe in Arnhem Land have been dated to about 65,000 years ago, a result that is widely cited and still discussed. The crossing from Island Southeast Asia required boats.",
    "Approximate. Settlement by about 50,000 years ago is widely accepted. Madjedbebe has been dated to about 65,000.",
)
add(
    "kimberley-rock-art",
    "Kimberley rock art",
    "history",
    -12000,
    -12000,
    -15.80,
    126.30,
    "Kimberley, Australia",
    "Oceania",
    "The Kimberley holds vast bodies of rock art, including the elegant Gwion figures. Some of that art is widely placed in the late Ice Age, around 12,000 years ago, and other paintings are much younger or still hard to date. The art belongs to Aboriginal traditions that continue.",
    "Approximate. Some Kimberley paintings are widely placed around 12,000 years ago, and many dates remain uncertain.",
)
add(
    "austronesian-voyages",
    "Austronesian voyages",
    "history",
    -3000,
    -1500,
    23.50,
    121.00,
    "Taiwan",
    "Asia",
    "Speakers of Austronesian languages left Taiwan around 3000 BCE and settled the Philippines, Indonesia, and Near Oceania. Archaeology and language both trace this expansion. The line is a schematic of the early voyaging, which later carried people into the remote Pacific and to Madagascar.",
    "Approximate. The expansion from Taiwan is widely dated to about 3000–1500 BCE.",
    path=[
        (23.5, 121.0),
        (15.0, 120.5),
        (7.0, 125.5),
        (-1.0, 121.0),
        (-5.0, 147.0),
    ],
)
add(
    "lapita",
    "Lapita settlement of Remote Oceania",
    "history",
    -1100,
    -800,
    -15.50,
    167.00,
    "Vanuatu and Tonga",
    "Oceania",
    "People making dentate-stamped Lapita pottery sailed beyond the Solomon Islands into Vanuatu, New Caledonia, Fiji, Tonga, and Samoa. That leap into Remote Oceania is widely dated to about 1100–800 BCE. It was the base from which later Polynesian cultures grew.",
    "Approximate. Lapita in Remote Oceania is widely dated to about 1100–800 BCE.",
)
add(
    "polynesian-voyages",
    "Polynesian settlement of the eastern Pacific",
    "history",
    900,
    1300,
    -13.83,
    -171.77,
    "Samoa to the Society Islands and Rapa Nui",
    "Oceania",
    "Polynesian navigators settled the Society Islands, Hawaiʻi, Rapa Nui, and Aotearoa between about 900 and 1300. They sailed double canoes by stars, swells, and birds. The line sketches one eastern route, from Samoa toward Tahiti and Rapa Nui.",
    "Approximate. Eastern Polynesia was settled between about 900 and 1300.",
    path=[
        (-13.8, -171.8),
        (-17.6, -149.5),
        (-27.1, -109.3),
    ],
)
add(
    "hawaii-settlement",
    "Settlement of Hawaiʻi",
    "history",
    1000,
    1200,
    19.70,
    -155.09,
    "Hawaiʻi island",
    "Oceania",
    "Polynesian voyagers settled the Hawaiian islands around 1000–1200. They brought crops, animals, and a language closely related to Māori and Tahitian. Later Hawaiian kingdoms grew from those founding communities.",
    "Approximate. Settlement is widely dated to about 1000–1200.",
)
add(
    "aotearoa-settlement",
    "Settlement of Aotearoa",
    "history",
    1250,
    1300,
    -36.85,
    174.76,
    "Aotearoa New Zealand",
    "Oceania",
    "Polynesian navigators settled Aotearoa New Zealand in the late thirteenth century. Radiocarbon dates and the extinction of the moa cluster around 1250–1300. Māori traditions remember the voyaging canoes that made the crossing.",
    "Approximate. Settlement is widely dated to about 1250–1300.",
)
add(
    "rapa-nui",
    "Settlement of Rapa Nui",
    "history",
    1200,
    1250,
    -27.12,
    -109.35,
    "Rapa Nui",
    "Oceania",
    "Rapa Nui, also called Easter Island, was settled by Polynesian voyagers around 1200. Older claims of a much earlier date have not held. The islanders later carved the moai, the great stone figures.",
    "Approximate. Current dating places settlement around 1200.",
)
add(
    "moai",
    "Moai of Rapa Nui",
    "history",
    1250,
    1500,
    -27.12,
    -109.35,
    "Rapa Nui",
    "Oceania",
    "Between about 1250 and 1500, people on Rapa Nui carved and raised hundreds of moai. The statues stood on stone platforms and faced inland over clan lands. Making and moving them required a large, organised community.",
    "Approximate. The main period of moai is widely dated to about 1250–1500.",
)
add(
    "madagascar-settlement",
    "Settlement of Madagascar",
    "history",
    500,
    1000,
    -18.93,
    47.52,
    "Madagascar",
    "Africa",
    "Madagascar was settled by people from Island Southeast Asia, with African communities joining them. Linguistic and genetic evidence places the main Austronesian arrival between about 500 and 1000. Malagasy is an Austronesian language with African influences.",
    "Approximate. The Austronesian settlement is widely placed between about 500 and 1000.",
)
add(
    "cook-pacific",
    "Cook's Pacific voyages",
    "history",
    1768,
    1779,
    -17.65,
    -149.43,
    "Tahiti and the Pacific",
    "Oceania",
    "James Cook's three voyages between 1768 and 1779 mapped much of the Pacific, including the east coast of Australia and Hawaiʻi. He was killed at Kealakekua Bay in 1779. The voyages opened the ocean to later European colonisation.",
    "The voyages are dated from 1768 to Cook's death on 14 February 1779.",
)
add(
    "kamehameha",
    "Kamehameha unites Hawaiʻi",
    "history",
    1810,
    1810,
    21.31,
    -157.86,
    "Hawaiʻi",
    "Oceania",
    "By 1810 Kamehameha I had brought the Hawaiian islands under one kingdom, after years of war. He used traditional alliances and European ships and guns. The kingdom lasted until the overthrow of 1893.",
    "The islands were united by 1810.",
)
add(
    "waitangi",
    "Treaty of Waitangi",
    "history",
    1840,
    1840,
    -35.26,
    174.08,
    "Waitangi, Aotearoa New Zealand",
    "Oceania",
    "On 6 February 1840 Māori chiefs and the British Crown signed the Treaty of Waitangi. The English and Māori texts do not say the same thing about sovereignty. The treaty is the founding document of the New Zealand state, and it remains disputed.",
    "The treaty was first signed on 6 February 1840.",
)
add(
    "new-zealand-wars",
    "New Zealand Wars",
    "history",
    1845,
    1872,
    -38.68,
    176.07,
    "Aotearoa New Zealand",
    "Oceania",
    "Wars between the Crown and Māori communities ran, with pauses, from 1845 to 1872. Large areas of Māori land were confiscated afterward. The fighting included the Waikato War of 1863–1864.",
    "The wars are dated from 1845 to 1872.",
)
add(
    "bikini-tests",
    "Nuclear tests at Bikini Atoll",
    "history",
    1946,
    1958,
    11.60,
    165.38,
    "Bikini Atoll, Marshall Islands",
    "Oceania",
    "The United States tested nuclear weapons at Bikini Atoll from 1946 to 1958, after removing the islanders. The 1954 Castle Bravo test was far larger than planned and irradiated the crew of a Japanese fishing boat and people on other atolls. Bikini remains largely uninhabitable.",
    "Tests ran from 1946 to 1958. Castle Bravo was on 1 March 1954.",
)
add(
    "australian-federation",
    "Federation of Australia",
    "history",
    1901,
    1901,
    -35.31,
    149.13,
    "Melbourne and Canberra's future site",
    "Oceania",
    "On 1 January 1901 the six Australian colonies federated as the Commonwealth of Australia. Indigenous Australians were excluded from the new political settlement. Canberra later became the capital.",
    "Federation took effect on 1 January 1901.",
)
add(
    "gallipoli",
    "Gallipoli campaign",
    "history",
    1915,
    1915,
    40.23,
    26.28,
    "Gallipoli, Turkey",
    "Europe",
    "In 1915 Allied forces, including large Australian and New Zealand contingents, landed at Gallipoli and failed to knock the Ottoman Empire out of the war. Both sides suffered very heavy casualties before the Allies withdrew. The campaign became a national story in Australia, New Zealand, and Turkey.",
    "The landings were on 25 April 1915. The evacuation ended in January 1916.",
)
add(
    "samoa-independence",
    "Independence of Samoa",
    "history",
    1962,
    1962,
    -13.83,
    -171.77,
    "Apia, Samoa",
    "Oceania",
    "Western Samoa became independent of New Zealand on 1 January 1962, the first Pacific island country to do so in that era. It later renamed itself the Independent State of Samoa. American Samoa remained a United States territory.",
    "Independence was on 1 January 1962.",
)
add(
    "fiji-independence",
    "Independence of Fiji",
    "history",
    1970,
    1970,
    -18.14,
    178.44,
    "Suva, Fiji",
    "Oceania",
    "Fiji became independent of Britain on 10 October 1970. The new state inherited a divided politics between indigenous Fijians and the descendants of Indian indentured labourers. Later coups showed how unsettled that settlement was.",
    "Independence was on 10 October 1970.",
)
add(
    "papua-independence",
    "Independence of Papua New Guinea",
    "history",
    1975,
    1975,
    -9.48,
    147.15,
    "Port Moresby, Papua New Guinea",
    "Oceania",
    "Papua New Guinea became independent of Australia on 16 September 1975. It is one of the most linguistically diverse countries in the world. The state joined a highland interior to coastal and island societies.",
    "Independence was on 16 September 1975.",
)
add(
    "rainbow-warrior",
    "Sinking of the Rainbow Warrior",
    "history",
    1985,
    1985,
    -36.84,
    174.76,
    "Auckland, Aotearoa New Zealand",
    "Oceania",
    "On 10 July 1985 French agents sank the Greenpeace ship Rainbow Warrior in Auckland harbour, killing the photographer Fernando Pereira. The ship had been preparing to protest French nuclear tests at Moruroa. France later admitted responsibility.",
    "The bombing was on 10 July 1985.",
)
add(
    "mabo-decision",
    "Mabo decision",
    "history",
    1992,
    1992,
    -10.60,
    142.20,
    "Murray Island, Australia",
    "Oceania",
    "In 1992 the High Court of Australia recognised native title in the Mabo case, brought by Eddie Mabo and others from Mer in the Torres Strait. The decision rejected the idea that Australia had been empty land at colonisation. A Native Title Act followed in 1993.",
    "The judgment was handed down on 3 June 1992.",
)
add(
    "maui-myth",
    "Māui fishes up islands",
    "myth",
    1854,
    1854,
    -36.85,
    174.76,
    "Aotearoa New Zealand",
    "Oceania",
    "Māori tradition tells how the ancestor Māui fished the North Island out of the sea from his canoe. The story is much older than writing in Aotearoa. Sir George Grey published a major written collection of these traditions in 1854.",
    "Earliest written source. Grey's Polynesian Mythology was published in 1854. The oral tradition is far older.",
)
add(
    "pele-myth",
    "Pele",
    "myth",
    1825,
    1830,
    19.42,
    -155.29,
    "Kīlauea, Hawaiʻi",
    "Oceania",
    "Pele is the volcano goddess of Hawaiʻi, at home in Kīlauea, and chants tell of her journey from Kahiki. The tradition is older than any book. Missionaries and Hawaiian writers set down versions in the early nineteenth century.",
    "Earliest written source. Written versions were recorded in the early nineteenth century. The tradition is older.",
)
add(
    "kumulipo",
    "Kumulipo",
    "myth",
    1700,
    1889,
    21.31,
    -157.86,
    "Hawaiʻi",
    "Oceania",
    "The Kumulipo is a Hawaiian chant of creation, composed for an eighteenth-century chief and later written down. It traces life from the coral polyp to the royal line. A famous published text appeared in the nineteenth century, long after the chant existed.",
    "Earliest written source. The chant belongs to the eighteenth century and was published in writing in the nineteenth. It records an older cosmology.",
)
add(
    "arrernte-written",
    "Arrernte ancestral narratives written down",
    "myth",
    1899,
    1899,
    -23.70,
    133.87,
    "Central Australia",
    "Oceania",
    "Arrernte and neighbouring peoples tell of ancestral beings who formed the country. Those traditions are vastly older than European contact. Spencer and Gillen's Native Tribes of Central Australia, published in 1899, was an early extended written record, not the beginning of the stories.",
    "Earliest written source. Spencer and Gillen published in 1899. The oral tradition is far older.",
)
add(
    "cook-antarctic-circle",
    "Cook crosses the Antarctic Circle",
    "history",
    1773,
    1773,
    -66.50,
    40.00,
    "Southern Ocean",
    "Antarctica",
    "On 17 January 1773 James Cook's Resolution crossed the Antarctic Circle, the first ship known to have done so. He circumnavigated the ice but did not sight the continent for certain. His voyage disproved the idea of a habitable southern continent reaching into temperate seas.",
    "The crossing was on 17 January 1773.",
)
add(
    "antarctica-sighted",
    "Sightings of Antarctica",
    "history",
    1820,
    1820,
    -69.00,
    -1.00,
    "Antarctic coast",
    "Antarctica",
    "In 1820 several expeditions saw the Antarctic ice coast. The Russian ships of Bellingshausen and Lazarev, and British and American sealers including Bransfield and Palmer, were all in those waters. No single 'first sighting' is undisputed, but the continent was seen that year.",
    "The sightings are dated to 1820.",
)
add(
    "amundsen-pole",
    "Amundsen reaches the South Pole",
    "history",
    1911,
    1911,
    -90.00,
    0.10,
    "South Pole",
    "Antarctica",
    "On 14 December 1911 Roald Amundsen and four companions reached the South Pole. They had set out from the Bay of Whales with dogsleds. They returned safely to their base.",
    "The party reached the pole on 14 December 1911.",
)
add(
    "scott-pole",
    "Scott at the South Pole",
    "history",
    1912,
    1912,
    -90.00,
    0.20,
    "South Pole",
    "Antarctica",
    "Robert Falcon Scott's party reached the South Pole on 17 January 1912 and found that Amundsen had been there first. All five men died on the return journey across the Ross Ice Shelf. Their diaries were found with the bodies the next summer.",
    "Scott reached the pole on 17 January 1912.",
)
add(
    "antarctic-treaty",
    "Antarctic Treaty",
    "history",
    1959,
    1959,
    -77.85,
    166.67,
    "Antarctica",
    "Antarctica",
    "Twelve countries signed the Antarctic Treaty in Washington on 1 December 1959. It set the continent aside for peaceful science and froze territorial claims. The treaty followed the International Geophysical Year of 1957–1958.",
    "The treaty was signed on 1 December 1959.",
)
add(
    "ozone-hole",
    "Antarctic ozone hole",
    "history",
    1985,
    1985,
    -75.58,
    -26.66,
    "Halley Research Station",
    "Antarctica",
    "In 1985 scientists from the British Antarctic Survey reported a deep springtime loss of ozone over Antarctica. The hole was linked to chlorofluorocarbons. The finding led to the Montreal Protocol of 1987, which phased those chemicals out.",
    "The paper was published in May 1985.",
)
add(
    "epica-dome-c",
    "EPICA Dome C ice core",
    "history",
    2004,
    2004,
    -75.10,
    123.35,
    "Dome C, Antarctica",
    "Antarctica",
    "In 2004 the European EPICA project finished drilling an ice core at Dome C that reached about 800,000 years of climate history. The core records repeated ice ages in trapped air and ice. It is a basic archive for the climate of the last several hundred thousand years.",
    "The bedrock drilling was completed in 2004.",
)
add(
    "larsen-b",
    "Collapse of Larsen B",
    "history",
    2002,
    2002,
    -65.50,
    -61.00,
    "Larsen B ice shelf",
    "Antarctica",
    "In early 2002 the Larsen B ice shelf on the Antarctic Peninsula collapsed over a few weeks. About 3,250 square kilometres of ice broke apart. The collapse followed strong regional warming and became a symbol of Antarctic change.",
    "The collapse was observed in January and March 2002.",
)
add(
    "maori-kingitanga",
    "Kīngitanga",
    "history",
    1858,
    1858,
    -38.00,
    175.30,
    "Waikato, Aotearoa New Zealand",
    "Oceania",
    "In 1858 Māori leaders installed Pōtatau Te Wherowhero as the first Māori king. The Kīngitanga was meant to unite tribes and hold land against colonial sale. It became a lasting institution, still based at Tūrangawaewae.",
    "Pōtatau was raised up as king in 1858.",
)
add(
    "moruroa",
    "French tests at Moruroa",
    "history",
    1966,
    1996,
    -21.83,
    -138.93,
    "Moruroa, French Polynesia",
    "Oceania",
    "France tested nuclear weapons at Moruroa and Fangataufa from 1966 to 1996, first in the air and later underground. Pacific governments and protest voyages opposed the tests. France ended them in 1996 after a final series and worldwide criticism.",
    "Atmospheric and underground tests ran from 1966 to 1996.",
)
add(
    "uluru-handback",
    "Handback of Uluru",
    "history",
    1985,
    1985,
    -25.34,
    131.04,
    "Uluru, Australia",
    "Oceania",
    "On 26 October 1985 the Australian government returned the title of Uluru to its Anangu traditional owners, who leased it back as a national park. The handback recognised a sacred place that had been taken for tourism. Climbing the rock was later banned.",
    "The handback was on 26 October 1985.",
)
add(
    "chatham-moriori",
    "Moriori of Rēkohu",
    "history",
    1500,
    1600,
    -43.95,
    -176.55,
    "Rēkohu, Chatham Islands",
    "Oceania",
    "Polynesian voyagers settled Rēkohu, the Chatham Islands, around 1500 and became the Moriori. They lived by a code that limited warfare. In 1835 Māori groups from Taranaki invaded and killed or enslaved many Moriori, a later and separate event.",
    "Approximate. Settlement is widely dated to about 1500.",
)
add(
    "kuk-swamp",
    "Kuk Swamp agriculture",
    "history",
    -7000,
    -5000,
    -5.78,
    144.33,
    "Kuk Swamp, Papua New Guinea",
    "Oceania",
    "At Kuk Swamp in the New Guinea highlands, drainage ditches and plant remains show early agriculture. The evidence is widely dated to about 7000–5000 BCE, and some features may be older. Highland New Guinea was an independent centre of plant domestication.",
    "Approximate. Early cultivation at Kuk is widely dated to about 7000–5000 BCE.",
)
add(
    "maize-balsas",
    "Domestication of maize",
    "history",
    -7000,
    -4000,
    18.35,
    -99.50,
    "Balsas valley, Mexico",
    "North America",
    "Maize was domesticated from the wild grass teosinte in the Balsas valley of south-western Mexico. The process was gradual and was underway by about 7000 BCE. Maize later became the staple of much of the Americas.",
    "Approximate. Domestication was underway by about 7000 BCE.",
)
add(
    "potato-andes",
    "Andean potatoes",
    "history",
    -5000,
    -3000,
    -13.50,
    -72.00,
    "Andean highlands, Peru",
    "South America",
    "People in the Andes domesticated the potato and other highland crops. Archaeological potatoes are widely dated to about 5000–3000 BCE. The crop later spread worldwide after the Spanish conquest.",
    "Approximate. Domesticated potatoes are widely in evidence by about 5000–3000 BCE.",
)
add(
    "dog-domestication",
    "Domestication of the dog",
    "history",
    -15000,
    -10000,
    48.00,
    70.00,
    "Eurasian steppe",
    "Asia",
    "Dogs are the first domesticated animal, descended from wolves. The place and the century are still debated, and estimates range from about 15,000 to more than 30,000 years ago. By the end of the Ice Age, dogs were living with people in Eurasia.",
    "Approximate. Dates differ by many thousands of years. A widely discussed range falls in the late Ice Age.",
)
add(
    "holocene-start",
    "Start of the Holocene",
    "history",
    -9700,
    -9700,
    72.58,
    -38.46,
    "Greenland ice",
    "North America",
    "About 11,700 years ago the Earth left the last glacial period and entered the Holocene, the warm epoch of farming and cities. The boundary is defined in a Greenland ice core. Sea levels rose for millennia afterward as the ice sheets melted.",
    "Approximate. The Holocene boundary is dated to about 11,700 years ago, around 9700 BCE.",
)
add(
    "younger-dryas",
    "Younger Dryas",
    "history",
    -10900,
    -9700,
    52.00,
    5.00,
    "North Atlantic",
    "Europe",
    "The Younger Dryas was a sharp return of cold lasting from about 12,900 to 11,700 years ago. It interrupted the warming at the end of the Ice Age, and it is recorded in ice cores and lake beds around the North Atlantic. Its cause is still discussed.",
    "Approximate. The cold interval is dated to about 12,900–11,700 years ago.",
)
add(
    "natufian",
    "Natufian communities",
    "history",
    -13000,
    -9500,
    32.95,
    35.30,
    "Levant",
    "Asia",
    "Natufian communities in the Levant built more permanent settlements and harvested wild cereals before full farming. They are widely dated to about 13,000–9,500 BCE. Some of the earliest known bread and beer come from this world.",
    "Approximate. The Natufian is widely dated to about 13,000–9,500 BCE.",
)
add(
    "ain-mallaha",
    "Ain Mallaha",
    "history",
    -12000,
    -10000,
    33.09,
    35.58,
    "Ain Mallaha, Israel",
    "Asia",
    "Ain Mallaha is a Natufian settlement with stone houses and a famous burial of a person with a dog. It was occupied around 12,000–10,000 BCE. The site shows village life beginning before agriculture was complete.",
    "Approximate. The settlement is widely dated to about 12,000–10,000 BCE.",
)
add(
    "uruk-city",
    "City of Uruk",
    "history",
    -4000,
    -3100,
    31.32,
    45.64,
    "Uruk, Iraq",
    "Asia",
    "Uruk grew into the first great city of Mesopotamia in the fourth millennium BCE, with monumental temples and tens of thousands of people. Writing appeared there near the end of this period. The city gives its name to the Uruk period.",
    "Approximate. The Uruk period is widely dated to about 4000–3100 BCE.",
)
add(
    "nile-hieroglyphs",
    "Early Egyptian hieroglyphs",
    "history",
    -3200,
    -3000,
    26.18,
    31.92,
    "Abydos, Egypt",
    "Africa",
    "Labels from royal tombs at Abydos show Egyptian hieroglyphs by about 3200 BCE. They name early kings and goods. Egyptian writing arose around the same centuries as Mesopotamian writing, and the two systems are distinct.",
    "Approximate. The earliest hieroglyphic labels are widely dated to about 3200–3000 BCE.",
)
